; NOTE: Assertions have been autogenerated by test/update_tpde_llc_test_checks.py UTC_ARGS: --version 5
; SPDX-FileCopyrightText: 2026 Contributors to TPDE <https://tpde.org>
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

; RUN: tpde-llc --target=x86_64 %s | %objdump | FileCheck %s -check-prefixes=X64

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define <4 x float> @many_fp_phis() {
; X64-LABEL: <many_fp_phis>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    pxor xmm1, xmm1
; X64-NEXT:    pxor xmm2, xmm2
; X64-NEXT:    pxor xmm3, xmm3
; X64-NEXT:    pxor xmm4, xmm4
; X64-NEXT:    pxor xmm5, xmm5
; X64-NEXT:    pxor xmm6, xmm6
; X64-NEXT:    pxor xmm7, xmm7
; X64-NEXT:    pxor xmm8, xmm8
; X64-NEXT:    pxor xmm9, xmm9
; X64-NEXT:    pxor xmm10, xmm10
; X64-NEXT:    pxor xmm11, xmm11
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movapd xmmword ptr [rbp - 0x40], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movapd xmmword ptr [rbp - 0x40], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movapd xmmword ptr [rbp - 0x40], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movapd xmmword ptr [rbp - 0x40], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movapd xmmword ptr [rbp - 0x40], xmm0
; X64-NEXT:    pxor xmm0, xmm0
; X64-NEXT:    movapd xmmword ptr [rbp - 0x40], xmm0
; X64-NEXT:    movapd xmm0, xmm2
; X64-NEXT:    pop rbp
; X64-NEXT:    ret
entry:
  br label %for.cond32.preheader.us.i

for.cond32.preheader.us.i:                        ; preds = %entry
  %wide.load.111353 = phi <4 x float> [ zeroinitializer, %entry ]
  %wide.load950.101350 = phi <4 x float> [ zeroinitializer, %entry ]
  %wide.load.101347 = phi <4 x float> [ zeroinitializer, %entry ]
  %wide.load950.91344 = phi <4 x float> [ zeroinitializer, %entry ]
  %wide.load.91341 = phi <4 x float> [ zeroinitializer, %entry ]
  %wide.load950.81338 = phi <4 x float> [ zeroinitializer, %entry ]
  %wide.load.81335 = phi <4 x float> [ zeroinitializer, %entry ]
  %wide.load950.71332 = phi <4 x float> [ zeroinitializer, %entry ]
  %wide.load.71329 = phi <4 x float> [ zeroinitializer, %entry ]
  %wide.load950.61326 = phi <4 x float> [ zeroinitializer, %entry ]
  %wide.load.61323 = phi <4 x float> [ zeroinitializer, %entry ]
  %wide.load950.51320 = phi <4 x float> [ zeroinitializer, %entry ]
  %wide.load.51317 = phi <4 x float> [ zeroinitializer, %entry ]
  %wide.load950.41314 = phi <4 x float> [ zeroinitializer, %entry ]
  %wide.load.41311 = phi <4 x float> [ zeroinitializer, %entry ]
  %wide.load950.31308 = phi <4 x float> [ zeroinitializer, %entry ]
  %wide.load.31305 = phi <4 x float> [ zeroinitializer, %entry ]
  ret <4 x float> %wide.load.31305
}
