; NOTE: Assertions have been autogenerated by test/update_tpde_llc_test_checks.py UTC_ARGS: --version 5
; SPDX-FileCopyrightText: 2025 Contributors to TPDE <https://tpde.org>
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

; RUN: tpde-llc --target=x86_64 %s | %objdump | FileCheck %s -check-prefixes=X64
; RUN: tpde-llc --target=aarch64 %s | %objdump | FileCheck %s -check-prefixes=ARM64
; XFAIL: llvm19.1
; XFAIL: llvm20.1

define i32 @phi_cycle() {
; X64-LABEL: <phi_cycle>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    push rbx
; X64-NEXT:    push r12
; X64-NEXT:    mov ebx, 0x1
; X64-NEXT:    mov r12d, 0x2
; X64-NEXT:  <L0>:
; X64-NEXT:    mov eax, r12d
; X64-NEXT:    mov r12d, ebx
; X64-NEXT:    mov ebx, eax
; X64-NEXT:    jmp <L0>
;
; ARM64-LABEL: <phi_cycle>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    stp x19, x20, [sp, #0x10]
; ARM64-NEXT:    mov x19, #0x1 // =1
; ARM64-NEXT:    mov x20, #0x2 // =2
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    mov w0, w20
; ARM64-NEXT:    mov w20, w19
; ARM64-NEXT:    mov w19, w0
; ARM64-NEXT:    b <L0>
  br label %1
1:
  %2 = phi i32 [ 1, %0 ], [ %3, %1 ]
  %3 = phi i32 [ 2, %0 ], [ %2, %1 ]
  br label %1
}

define i32 @phi_unicycle() {
; X64-LABEL: <phi_unicycle>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    push rbx
; X64-NEXT:    push r12
; X64-NEXT:    mov ebx, 0x1
; X64-NEXT:    mov r12d, 0x2
; X64-NEXT:  <L0>:
; X64-NEXT:    jmp <L0>
;
; ARM64-LABEL: <phi_unicycle>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    stp x19, x20, [sp, #0x10]
; ARM64-NEXT:    mov x19, #0x1 // =1
; ARM64-NEXT:    mov x20, #0x2 // =2
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    b <L0>
  br label %1
1:
  %2 = phi i32 [ 1, %0 ], [ %2, %1 ]
  %3 = phi i32 [ 2, %0 ], [ %3, %1 ]
  br label %1
}

define ptr @phi_twocycles() {
; X64-LABEL: <phi_twocycles>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    push rbx
; X64-NEXT:    push r12
; X64-NEXT:    push r13
; X64-NEXT:    push r14
; X64-NEXT:    mov ebx, 0x1
; X64-NEXT:    mov r12d, 0x2
; X64-NEXT:    mov r13d, 0x3
; X64-NEXT:    mov r14d, 0x4
; X64-NEXT:  <L0>:
; X64-NEXT:    mov eax, r12d
; X64-NEXT:    mov r12d, ebx
; X64-NEXT:    mov ebx, eax
; X64-NEXT:    mov eax, r14d
; X64-NEXT:    mov r14d, r13d
; X64-NEXT:    mov r13d, eax
; X64-NEXT:    jmp <L0>
;
; ARM64-LABEL: <phi_twocycles>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    stp x19, x20, [sp, #0x10]
; ARM64-NEXT:    stp x21, x22, [sp, #0x20]
; ARM64-NEXT:    mov x19, #0x1 // =1
; ARM64-NEXT:    mov x20, #0x2 // =2
; ARM64-NEXT:    mov x21, #0x3 // =3
; ARM64-NEXT:    mov x22, #0x4 // =4
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    mov w0, w20
; ARM64-NEXT:    mov w20, w19
; ARM64-NEXT:    mov w19, w0
; ARM64-NEXT:    mov w0, w22
; ARM64-NEXT:    mov w22, w21
; ARM64-NEXT:    mov w21, w0
; ARM64-NEXT:    b <L0>
  br label %1

1:                                                ; preds = %1, %0
  %2 = phi i32 [ 1, %0 ], [ %3, %1 ]
  %3 = phi i32 [ 2, %0 ], [ %2, %1 ]
  %4 = phi i32 [ 3, %0 ], [ %5, %1 ]
  %5 = phi i32 [ 4, %0 ], [ %4, %1 ]
  br label %1
}

define ptr @phi_cycles_selfref() {
; X64-LABEL: <phi_cycles_selfref>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    push rbx
; X64-NEXT:    push r12
; X64-NEXT:    push r13
; X64-NEXT:    mov ebx, 0x1
; X64-NEXT:    mov r12d, 0x2
; X64-NEXT:    mov r13d, 0x3
; X64-NEXT:  <L0>:
; X64-NEXT:    mov eax, r12d
; X64-NEXT:    mov r12d, ebx
; X64-NEXT:    mov ebx, eax
; X64-NEXT:    jmp <L0>
;
; ARM64-LABEL: <phi_cycles_selfref>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    stp x19, x20, [sp, #0x10]
; ARM64-NEXT:    str x21, [sp, #0x20]
; ARM64-NEXT:    mov x19, #0x1 // =1
; ARM64-NEXT:    mov x20, #0x2 // =2
; ARM64-NEXT:    mov x21, #0x3 // =3
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    mov w0, w20
; ARM64-NEXT:    mov w20, w19
; ARM64-NEXT:    mov w19, w0
; ARM64-NEXT:    b <L0>
  br label %1

1:                                                ; preds = %1, %0
  %2 = phi i32 [ 1, %0 ], [ %3, %1 ]
  %3 = phi i32 [ 2, %0 ], [ %2, %1 ]
  %4 = phi i32 [ 3, %0 ], [ %4, %1 ]
  br label %1
}

define void @phi_cycle_i128(i1 %c, i128 %v1, i128 %v2) {
; X64-LABEL: <phi_cycle_i128>:
; X64:         mov rdi, rcx
; X64-NEXT:  <L0>:
; X64-NEXT:    mov rax, rdi
; X64-NEXT:    mov rdi, rsi
; X64-NEXT:    mov rsi, rax
; X64-NEXT:    mov rax, r8
; X64-NEXT:    mov r8, rdx
; X64-NEXT:    mov rdx, rax
; X64-NEXT:    jmp <L0>
;
; ARM64-LABEL: <phi_cycle_i128>:
; ARM64:       <L0>:
; ARM64-NEXT:    mov x0, x4
; ARM64-NEXT:    mov x4, x2
; ARM64-NEXT:    mov x2, x0
; ARM64-NEXT:    mov x0, x5
; ARM64-NEXT:    mov x5, x3
; ARM64-NEXT:    mov x3, x0
; ARM64-NEXT:    b <phi_cycle_i128>
  br label %1

1:
  %2 = phi i128 [ %v1, %0 ], [ %3, %1 ]
  %3 = phi i128 [ %v2, %0 ], [ %2, %1 ]
  br label %1
}

define void @phi_cycle_multipart(i1 %c, [4 x i64] %v1, [4 x i64] %v2) {
; X64-LABEL: <phi_cycle_multipart>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    push rbx
; X64-NEXT:    mov rax, qword ptr [rbp + 0x10]
; X64-NEXT:    mov rdi, qword ptr [rbp + 0x18]
; X64-NEXT:    mov r10, qword ptr [rbp + 0x20]
; X64-NEXT:    mov rbx, rcx
; X64-NEXT:  <L0>:
; X64-NEXT:    mov rcx, r9
; X64-NEXT:    mov r9, rsi
; X64-NEXT:    mov rsi, rcx
; X64-NEXT:    mov rcx, rax
; X64-NEXT:    mov rax, rdx
; X64-NEXT:    mov rdx, rcx
; X64-NEXT:    mov rcx, rdi
; X64-NEXT:    mov rdi, rbx
; X64-NEXT:    mov rbx, rcx
; X64-NEXT:    mov rcx, r10
; X64-NEXT:    mov r10, r8
; X64-NEXT:    mov r8, rcx
; X64-NEXT:    jmp <L0>
;
; ARM64-LABEL: <phi_cycle_multipart>:
; ARM64:         mov x17, sp
; ARM64-NEXT:    ldr x0, [x17]
; ARM64-NEXT:    ldr x9, [x17, #0x8]
; ARM64-NEXT:    ldr x10, [x17, #0x10]
; ARM64-NEXT:    ldr x11, [x17, #0x18]
; ARM64-NEXT:    mov x6, x1
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    mov x1, x0
; ARM64-NEXT:    mov x0, x6
; ARM64-NEXT:    mov x6, x1
; ARM64-NEXT:    mov x1, x9
; ARM64-NEXT:    mov x9, x2
; ARM64-NEXT:    mov x2, x1
; ARM64-NEXT:    mov x1, x10
; ARM64-NEXT:    mov x10, x3
; ARM64-NEXT:    mov x3, x1
; ARM64-NEXT:    mov x1, x11
; ARM64-NEXT:    mov x11, x4
; ARM64-NEXT:    mov x4, x1
; ARM64-NEXT:    b <L0>
  br label %1

1:
  %2 = phi [4 x i64] [ %v1, %0 ], [ %3, %1 ]
  %3 = phi [4 x i64] [ %v2, %0 ], [ %2, %1 ]
  br label %1
}

define i32 @phi_last_use(i1 %c, i32 %a, i32 %b) {
; X64-LABEL: <phi_last_use>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    push rbx
; X64-NEXT:    push r12
; X64-NEXT:    mov ebx, esi
; X64-NEXT:    test dil, 0x1
; X64-NEXT:    je <L0>
; X64-NEXT:    xor r12d, r12d
; X64-NEXT:    jmp <L2>
; X64-NEXT:  <L0>:
; X64-NEXT:    lea eax, [rbx + 0x1]
; X64-NEXT:    test eax, eax
; X64-NEXT:    je <L1>
; X64-NEXT:    mov dword ptr [rbp - 0x2c], eax
; X64-NEXT:    jmp <L0>
; X64-NEXT:  <L1>:
; X64-NEXT:    mov r12d, eax
; X64-NEXT:  <L2>:
; X64-NEXT:    mov eax, r12d
; X64-NEXT:    pop r12
; X64-NEXT:    pop rbx
; X64-NEXT:    pop rbp
; X64-NEXT:    ret
;
; ARM64-LABEL: <phi_last_use>:
; ARM64:         stp x29, x30, [sp, #-0xb0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    stp x19, x20, [sp, #0x10]
; ARM64-NEXT:    mov w19, w1
; ARM64-NEXT:    tst w0, #0x1
; ARM64-NEXT:    b.eq <L0>
; ARM64-NEXT:    mov w20, #0x0 // =0
; ARM64-NEXT:    b <L2>
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    add w0, w19, #0x1
; ARM64-NEXT:    mov w1, w0
; ARM64-NEXT:    cbz w1, <L1>
; ARM64-NEXT:    str w0, [x29, #0xa0]
; ARM64-NEXT:    b <L0>
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    mov w20, w0
; ARM64-NEXT:  <L2>:
; ARM64-NEXT:    mov w0, w20
; ARM64-NEXT:    ldp x19, x20, [sp, #0x10]
; ARM64-NEXT:    ldp x29, x30, [sp], #0xb0
; ARM64-NEXT:    ret
entry:
  br i1 %c, label %ret, label %loop
loop:
  %add = add i32 %a, 1
  %cmp = icmp eq i32 %add, 0
  br i1 %cmp, label %ret, label %loop
ret:
  %rv = phi i32 [ 0, %entry ], [ %add, %loop ]
  ret i32 %rv
}
