; NOTE: Assertions have been autogenerated by test/update_tpde_llc_test_checks.py UTC_ARGS: --version 5
; SPDX-FileCopyrightText: 2025 Contributors to TPDE <https://tpde.org>
;
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

; RUN: tpde-llc --target=x86_64 %s | llvm-objdump -d -r --symbolize-operands --x86-asm-syntax=intel - | FileCheck %s -check-prefixes=X64
; RUN: tpde-llc --target=aarch64 %s | %objdump | FileCheck %s -check-prefixes=ARM64
; XFAIL: llvm19.1
; XFAIL: llvm20.1

define i32 @empty_switch(i32 %0) {
; X64-LABEL: <empty_switch>:
; X64:         0: e9 00 00 00 00 jmp <L0>
; X64-NEXT:  <L0>:
; X64-NEXT:    5: e9 00 00 00 00 jmp <L1>
; X64-NEXT:  <L1>:
; X64-NEXT:    a: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:    f: c3 ret
;
; ARM64-LABEL: <empty_switch>:
; ARM64:         b <L0>
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    b <L1>
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default []
default:
  ret i32 -1
}

define i32 @basic_switch(i32 %0) {
; X64-LABEL: <basic_switch>:
; X64:         10: 83 ff 00 cmp edi, 0x0
; X64-NEXT:    13: 0f 84 23 00 00 00 je <L1>
; X64-NEXT:    19: 83 ff 01 cmp edi, 0x1
; X64-NEXT:    1c: 0f 84 22 00 00 00 je <L2>
; X64-NEXT:    22: 83 ff 02 cmp edi, 0x2
; X64-NEXT:    25: 0f 84 21 00 00 00 je <L3>
; X64-NEXT:    2b: e9 00 00 00 00 jmp <L0>
; X64-NEXT:  <L0>:
; X64-NEXT:    30: e9 37 00 00 00 jmp <L7>
; X64-NEXT:    35: 0f 1f 80 00 00 00 00 nop dword ptr [rax]
; X64-NEXT:  <L1>:
; X64-NEXT:    3c: e9 10 00 00 00 jmp <L4>
; X64-NEXT:    41: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L2>:
; X64-NEXT:    44: e9 0f 00 00 00 jmp <L5>
; X64-NEXT:    49: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L3>:
; X64-NEXT:    4c: e9 11 00 00 00 jmp <L6>
; X64-NEXT:  <L4>:
; X64-NEXT:    51: 31 c0 xor eax, eax
; X64-NEXT:    53: e9 19 00 00 00 jmp <L8>
; X64-NEXT:  <L5>:
; X64-NEXT:    58: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    5d: e9 0f 00 00 00 jmp <L8>
; X64-NEXT:  <L6>:
; X64-NEXT:    62: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    67: e9 05 00 00 00 jmp <L8>
; X64-NEXT:  <L7>:
; X64-NEXT:    6c: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:  <L8>:
; X64-NEXT:    71: c3 ret
; X64-NEXT:    72: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    7b: 0f 1f 44 00 00 nop dword ptr [rax + rax]
;
; ARM64-LABEL: <basic_switch>:
; ARM64:         cmp w0, #0x0
; ARM64-NEXT:    b.eq <L1>
; ARM64-NEXT:    cmp w0, #0x1
; ARM64-NEXT:    b.eq <L2>
; ARM64-NEXT:    cmp w0, #0x2
; ARM64-NEXT:    b.eq <L3>
; ARM64-NEXT:    b <L0>
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    b <L7>
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    b <L4>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:  <L2>:
; ARM64-NEXT:    b <L5>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:  <L3>:
; ARM64-NEXT:    b <L6>
; ARM64-NEXT:  <L4>:
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    b <L8>
; ARM64-NEXT:  <L5>:
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    b <L8>
; ARM64-NEXT:  <L6>:
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    b <L8>
; ARM64-NEXT:  <L7>:
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:  <L8>:
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default [ i32 0, label %eq0
                                  i32 1, label %eq1
                                  i32 2, label %eq2]
eq0:
  ret i32 0
eq1:
  ret i32 1
eq2:
  ret i32 2
default:
  ret i32 -1
}

define i32 @switch_table(i32 %0) {
; x64-label: switch_table>:
; x64:    b0: 55 push rbp
; x64:    b1: 48 89 e5 mov rbp, rsp
; x64:    b4: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; x64:    bd: 48 81 ec 10 00 00 00 sub rsp, 0x10
; x64:    c4: 83 ff 06 cmp edi, 0x6
; x64:    c7: 0f 87 2f 00 00 00 ja <l0>
; x64:    cd: 89 ff mov edi, edi
; x64:    cf: 48 8d 05 0a 00 00 00 lea rax, <switch_table+0x30>
; x64:    d6: 48 63 3c b8 movsxd rdi, dword ptr [rax + 4*rdi]
; x64:    da: 48 01 f8 add rax, rdi
; x64:    dd: ff e0 jmp rax
; x64:    df: 00 21 add byte ptr [rcx], ah
; x64:    e1: 00 00 add byte ptr [rax], al
; x64:    e3: 00 26 add byte ptr [rsi], ah
; x64:    e5: 00 00 add byte ptr [rax], al
; x64:    e7: 00 2b add byte ptr [rbx], ch
; x64:    e9: 00 00 add byte ptr [rax], al
; x64:    eb: 00 1c 00 add byte ptr [rax + rax], bl
; x64:    ee: 00 00 add byte ptr [rax], al
; x64:    f0: 30 00 xor byte ptr [rax], al
; x64:    f2: 00 00 add byte ptr [rax], al
; x64:    f4: 35 00 00 00 3a xor eax, 0x3a000000
; x64:    f9: 00 00 add byte ptr [rax], al
; x64:    fb: 00 e9 add cl, ch
; x64:    fd: a8 00 test al, 0x0
; x64:    ff: 00 00 add byte ptr [rax], al
; x64:    101: e9 19 00 00 00 jmp <l1>
; x64:    106: e9 2b 00 00 00 jmp <l2>
; x64:    10b: e9 3d 00 00 00 jmp <l3>
; x64:    110: e9 4f 00 00 00 jmp <l4>
; x64:    115: e9 61 00 00 00 jmp <l5>
; x64:    11a: e9 73 00 00 00 jmp <l6>
; x64:  <l1>:
; x64:    11f: b8 00 00 00 00 mov eax, 0x0
; x64:    124: 48 83 c4 10 add rsp, 0x10
; x64:    128: 5d pop rbp
; x64:    129: c3 ret
; x64:  <l2>:
; x64:    136: b8 01 00 00 00 mov eax, 0x1
; x64:    13b: 48 83 c4 10 add rsp, 0x10
; x64:    13f: 5d pop rbp
; x64:    140: c3 ret
; x64:  <l3>:
; x64:    14d: b8 02 00 00 00 mov eax, 0x2
; x64:    152: 48 83 c4 10 add rsp, 0x10
; x64:    156: 5d pop rbp
; x64:    157: c3 ret
; x64:  <l4>:
; x64:    164: b8 04 00 00 00 mov eax, 0x4
; x64:    169: 48 83 c4 10 add rsp, 0x10
; x64:    16d: 5d pop rbp
; x64:    16e: c3 ret
; x64:  <l5>:
; x64:    17b: b8 05 00 00 00 mov eax, 0x5
; x64:    180: 48 83 c4 10 add rsp, 0x10
; x64:    184: 5d pop rbp
; x64:    185: c3 ret
; x64:  <l6>:
; x64:    192: b8 06 00 00 00 mov eax, 0x6
; x64:    197: 48 83 c4 10 add rsp, 0x10
; x64:    19b: 5d pop rbp
; x64:    19c: c3 ret
; x64:    1a9: b8 ff ff ff ff mov eax, 0xffffffff
; x64:    1ae: 48 83 c4 10 add rsp, 0x10
; x64:    1b2: 5d pop rbp
; x64:    1b3: c3 ret
; x64:     ...
; X64-LABEL: <switch_table>:
; X64:         80: 83 ff 06 cmp edi, 0x6
; X64-NEXT:    83: 0f 87 14 00 00 00 ja <L0>
; X64-NEXT:    89: 89 ff mov edi, edi
; X64-NEXT:    8b: 48 8d 15 7e 00 00 00 lea rdx, <switch_table+0x90>
; X64-NEXT:    92: 8b 3c ba mov edi, dword ptr [rdx + 4*rdi]
; X64-NEXT:    95: 48 29 fa sub rdx, rdi
; X64-NEXT:    98: ff e2 jmp rdx
; X64-NEXT:    9a: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L0>:
; X64-NEXT:    9d: e9 68 00 00 00 jmp <L7>
; X64-NEXT:    a2: 66 90 nop
; X64-NEXT:    a4: e9 28 00 00 00 jmp <L1>
; X64-NEXT:    a9: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    ac: e9 27 00 00 00 jmp <L2>
; X64-NEXT:    b1: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    b4: e9 29 00 00 00 jmp <L3>
; X64-NEXT:    b9: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    bc: e9 2b 00 00 00 jmp <L4>
; X64-NEXT:    c1: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    c4: e9 2d 00 00 00 jmp <L5>
; X64-NEXT:    c9: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    cc: e9 2f 00 00 00 jmp <L6>
; X64-NEXT:  <L1>:
; X64-NEXT:    d1: 31 c0 xor eax, eax
; X64-NEXT:    d3: e9 37 00 00 00 jmp <L8>
; X64-NEXT:  <L2>:
; X64-NEXT:    d8: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    dd: e9 2d 00 00 00 jmp <L8>
; X64-NEXT:  <L3>:
; X64-NEXT:    e2: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    e7: e9 23 00 00 00 jmp <L8>
; X64-NEXT:  <L4>:
; X64-NEXT:    ec: b8 04 00 00 00 mov eax, 0x4
; X64-NEXT:    f1: e9 19 00 00 00 jmp <L8>
; X64-NEXT:  <L5>:
; X64-NEXT:    f6: b8 05 00 00 00 mov eax, 0x5
; X64-NEXT:    fb: e9 0f 00 00 00 jmp <L8>
; X64-NEXT:  <L6>:
; X64-NEXT:    100: b8 06 00 00 00 mov eax, 0x6
; X64-NEXT:    105: e9 05 00 00 00 jmp <L8>
; X64-NEXT:  <L7>:
; X64-NEXT:    10a: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:  <L8>:
; X64-NEXT:    10f: c3 ret
; X64-NEXT:    110: 6c insb byte ptr es:[rdi], dx
; X64-NEXT:    111: 00 00 add byte ptr [rax], al
; X64-NEXT:    113: 00 64 00 00 add byte ptr [rax + rax], ah
; X64-NEXT:    117: 00 5c 00 00 add byte ptr [rax + rax], bl
; X64-NEXT:    11b: 00 73 00 add byte ptr [rbx], dh
; X64-NEXT:    11e: 00 00 add byte ptr [rax], al
; X64-NEXT:    120: 54 push rsp
; X64-NEXT:    121: 00 00 add byte ptr [rax], al
; X64-NEXT:    123: 00 4c 00 00 add byte ptr [rax + rax], cl
; X64-NEXT:    127: 00 44 00 00 add byte ptr [rax + rax], al
; X64-NEXT:    12b: 00 0f add byte ptr [rdi], cl
; X64-NEXT:    12d: 1f <unknown>
; X64-NEXT:    12e: 40 00 83 ef 03 83 ff add byte ptr [rbx - 0x7cfc11], al
;
; ARM64-LABEL: <switch_table>:
; ARM64:         cmp w0, #0x6
; ARM64-NEXT:    b.hi <L1>
; ARM64-NEXT:    adrp x2, 0x0 <empty_switch>
; ARM64-NEXT:     R_AARCH64_ADR_PREL_PG_HI21
; ARM64-NEXT:    add x2, x2, #0x0
; ARM64-NEXT:     R_AARCH64_ADD_ABS_LO12_NC
; ARM64-NEXT:    ldrb w0, [x2, w0, uxtw #0]
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    adr x2, <L0>
; ARM64-NEXT:    add x2, x2, x0, lsl #2
; ARM64-NEXT:    br x2
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    b <L8>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L2>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L3>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L4>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L5>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L6>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L7>
; ARM64-NEXT:  <L2>:
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:  <L3>:
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:  <L4>:
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:  <L5>:
; ARM64-NEXT:    mov x0, #0x4 // =4
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:  <L6>:
; ARM64-NEXT:    mov x0, #0x5 // =5
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:  <L7>:
; ARM64-NEXT:    mov x0, #0x6 // =6
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:  <L8>:
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:  <L9>:
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default [
    i32 0, label %eq0
    i32 1, label %eq1
    i32 2, label %eq2
    i32 4, label %eq4
    i32 5, label %eq5
    i32 6, label %eq6]
eq0:
  ret i32 0
eq1:
  ret i32 1
eq2:
  ret i32 2
eq4:
  ret i32 4
eq5:
  ret i32 5
eq6:
  ret i32 6
default:
  ret i32 -1
}

define i32 @switch_table2(i32 %0) {
; X64-LABEL: <switch_table2>:
; X64:         130: 83 ef 03 sub edi, 0x3
; X64-NEXT:    133: 83 ff 06 cmp edi, 0x6
; X64-NEXT:    136: 0f 87 12 00 00 00 ja <L0>
; X64-NEXT:    13c: 48 8d 15 81 00 00 00 lea rdx, <switch_table2+0x94>
; X64-NEXT:    143: 8b 3c ba mov edi, dword ptr [rdx + 4*rdi]
; X64-NEXT:    146: 48 29 fa sub rdx, rdi
; X64-NEXT:    149: ff e2 jmp rdx
; X64-NEXT:    14b: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L0>:
; X64-NEXT:    14e: e9 6a 00 00 00 jmp <L7>
; X64-NEXT:    153: 90 nop
; X64-NEXT:    154: e9 28 00 00 00 jmp <L1>
; X64-NEXT:    159: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    15c: e9 2a 00 00 00 jmp <L2>
; X64-NEXT:    161: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    164: e9 2c 00 00 00 jmp <L3>
; X64-NEXT:    169: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    16c: e9 2e 00 00 00 jmp <L4>
; X64-NEXT:    171: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    174: e9 30 00 00 00 jmp <L5>
; X64-NEXT:    179: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    17c: e9 32 00 00 00 jmp <L6>
; X64-NEXT:  <L1>:
; X64-NEXT:    181: b8 03 00 00 00 mov eax, 0x3
; X64-NEXT:    186: e9 37 00 00 00 jmp <L8>
; X64-NEXT:  <L2>:
; X64-NEXT:    18b: b8 04 00 00 00 mov eax, 0x4
; X64-NEXT:    190: e9 2d 00 00 00 jmp <L8>
; X64-NEXT:  <L3>:
; X64-NEXT:    195: b8 05 00 00 00 mov eax, 0x5
; X64-NEXT:    19a: e9 23 00 00 00 jmp <L8>
; X64-NEXT:  <L4>:
; X64-NEXT:    19f: b8 07 00 00 00 mov eax, 0x7
; X64-NEXT:    1a4: e9 19 00 00 00 jmp <L8>
; X64-NEXT:  <L5>:
; X64-NEXT:    1a9: b8 08 00 00 00 mov eax, 0x8
; X64-NEXT:    1ae: e9 0f 00 00 00 jmp <L8>
; X64-NEXT:  <L6>:
; X64-NEXT:    1b3: b8 09 00 00 00 mov eax, 0x9
; X64-NEXT:    1b8: e9 05 00 00 00 jmp <L8>
; X64-NEXT:  <L7>:
; X64-NEXT:    1bd: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:  <L8>:
; X64-NEXT:    1c2: c3 ret
; X64-NEXT:    1c3: 90 nop
; X64-NEXT:    1c4: 70 00 jo <L9>
; X64-NEXT:  <L9>:
; X64-NEXT:    1c6: 00 00 add byte ptr [rax], al
; X64-NEXT:    1c8: 68 00 00 00 60 push 0x60000000
; X64-NEXT:    1cd: 00 00 add byte ptr [rax], al
; X64-NEXT:    1cf: 00 76 00 add byte ptr [rsi], dh
; X64-NEXT:    1d2: 00 00 add byte ptr [rax], al
; X64-NEXT:    1d4: 58 pop rax
; X64-NEXT:    1d5: 00 00 add byte ptr [rax], al
; X64-NEXT:    1d7: 00 50 00 add byte ptr [rax], dl
; X64-NEXT:    1da: 00 00 add byte ptr [rax], al
; X64-NEXT:    1dc: 48 00 00 add byte ptr [rax], al
; X64-NEXT:    1df: 00 81 ff e9 03 00 add byte ptr [rcx + 0x3e9ff], al
;
; ARM64-LABEL: <switch_table2>:
; ARM64:         sub w0, w0, #0x3
; ARM64-NEXT:    cmp w0, #0x6
; ARM64-NEXT:    b.hi <L1>
; ARM64-NEXT:    adrp x2, 0x0 <empty_switch>
; ARM64-NEXT:     R_AARCH64_ADR_PREL_PG_HI21
; ARM64-NEXT:    add x2, x2, #0x0
; ARM64-NEXT:     R_AARCH64_ADD_ABS_LO12_NC
; ARM64-NEXT:    ldrb w0, [x2, w0, uxtw #0]
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    adr x2, <L0>
; ARM64-NEXT:    add x2, x2, x0, lsl #2
; ARM64-NEXT:    br x2
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    b <L8>
; ARM64-NEXT:    b <L2>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L3>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L4>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L5>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L6>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L7>
; ARM64-NEXT:  <L2>:
; ARM64-NEXT:    mov x0, #0x3 // =3
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:  <L3>:
; ARM64-NEXT:    mov x0, #0x4 // =4
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:  <L4>:
; ARM64-NEXT:    mov x0, #0x5 // =5
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:  <L5>:
; ARM64-NEXT:    mov x0, #0x7 // =7
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:  <L6>:
; ARM64-NEXT:    mov x0, #0x8 // =8
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:  <L7>:
; ARM64-NEXT:    mov x0, #0x9 // =9
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:  <L8>:
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:  <L9>:
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default [
    i32 3, label %eq3
    i32 4, label %eq4
    i32 5, label %eq5
    i32 7, label %eq7
    i32 8, label %eq8
    i32 9, label %eq9]
eq3:
  ret i32 3
eq4:
  ret i32 4
eq5:
  ret i32 5
eq7:
  ret i32 7
eq8:
  ret i32 8
eq9:
  ret i32 9
default:
  ret i32 -1
}

define i32 @switch_table3(i32 %0) {
; X64-LABEL: <switch_table3>:
; X64:         1e0: 81 ff e9 03 00 00 cmp edi, 0x3e9
; X64-NEXT:    1e6: 0f 84 80 00 00 00 je <L2>
; X64-NEXT:    1ec: 0f 87 1e 00 00 00 ja <L0>
; X64-NEXT:    1f2: 83 ef 01 sub edi, 0x1
; X64-NEXT:    1f5: 83 ff 05 cmp edi, 0x5
; X64-NEXT:    1f8: 0f 87 33 00 00 00 ja <L1>
; X64-NEXT:    1fe: 48 8d 15 bb 00 00 00 lea rdx, <switch_table3+0xe0>
; X64-NEXT:    205: 8b 3c ba mov edi, dword ptr [rdx + 4*rdi]
; X64-NEXT:    208: 48 29 fa sub rdx, rdi
; X64-NEXT:    20b: ff e2 jmp rdx
; X64-NEXT:    20d: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L0>:
; X64-NEXT:    210: 81 ef ea 03 00 00 sub edi, 0x3ea
; X64-NEXT:    216: 83 ff 04 cmp edi, 0x4
; X64-NEXT:    219: 0f 87 12 00 00 00 ja <L1>
; X64-NEXT:    21f: 48 8d 15 b2 00 00 00 lea rdx, <switch_table3+0xf8>
; X64-NEXT:    226: 8b 3c ba mov edi, dword ptr [rdx + 4*rdi]
; X64-NEXT:    229: 48 29 fa sub rdx, rdi
; X64-NEXT:    22c: ff e2 jmp rdx
; X64-NEXT:    22e: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L1>:
; X64-NEXT:    231: e9 81 00 00 00 jmp <L6>
; X64-NEXT:    236: 66 0f 1f 44 00 00 nop word ptr [rax + rax]
; X64-NEXT:    23c: e9 58 00 00 00 jmp <L3>
; X64-NEXT:    241: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    244: e9 5a 00 00 00 jmp <L4>
; X64-NEXT:    249: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    24c: e9 5c 00 00 00 jmp <L5>
; X64-NEXT:    251: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    254: e9 40 00 00 00 jmp <L3>
; X64-NEXT:    259: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    25c: e9 42 00 00 00 jmp <L4>
; X64-NEXT:    261: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    264: e9 44 00 00 00 jmp <L5>
; X64-NEXT:    269: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L2>:
; X64-NEXT:    26c: e9 28 00 00 00 jmp <L3>
; X64-NEXT:    271: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    274: e9 2a 00 00 00 jmp <L4>
; X64-NEXT:    279: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    27c: e9 2c 00 00 00 jmp <L5>
; X64-NEXT:    281: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    284: e9 10 00 00 00 jmp <L3>
; X64-NEXT:    289: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    28c: e9 12 00 00 00 jmp <L4>
; X64-NEXT:    291: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    294: e9 14 00 00 00 jmp <L5>
; X64-NEXT:  <L3>:
; X64-NEXT:    299: b8 03 00 00 00 mov eax, 0x3
; X64-NEXT:    29e: e9 19 00 00 00 jmp <L7>
; X64-NEXT:  <L4>:
; X64-NEXT:    2a3: b8 04 00 00 00 mov eax, 0x4
; X64-NEXT:    2a8: e9 0f 00 00 00 jmp <L7>
; X64-NEXT:  <L5>:
; X64-NEXT:    2ad: b8 05 00 00 00 mov eax, 0x5
; X64-NEXT:    2b2: e9 05 00 00 00 jmp <L7>
; X64-NEXT:  <L6>:
; X64-NEXT:    2b7: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:  <L7>:
; X64-NEXT:    2bc: c3 ret
; X64-NEXT:    2bd: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    2c0: 84 00 test byte ptr [rax], al
; X64-NEXT:    2c2: 00 00 add byte ptr [rax], al
; X64-NEXT:    2c4: 7c 00 jl <L8>
; X64-NEXT:  <L8>:
; X64-NEXT:    2c6: 00 00 add byte ptr [rax], al
; X64-NEXT:    2c8: 74 00 je <L9>
; X64-NEXT:  <L9>:
; X64-NEXT:    2ca: 00 00 add byte ptr [rax], al
; X64-NEXT:    2cc: 6c insb byte ptr es:[rdi], dx
; X64-NEXT:    2cd: 00 00 add byte ptr [rax], al
; X64-NEXT:    2cf: 00 64 00 00 add byte ptr [rax + rax], ah
; X64-NEXT:    2d3: 00 5c 00 00 add byte ptr [rax + rax], bl
; X64-NEXT:    2d7: 00 64 00 00 add byte ptr [rax + rax], ah
; X64-NEXT:    2db: 00 5c 00 00 add byte ptr [rax + rax], bl
; X64-NEXT:    2df: 00 54 00 00 add byte ptr [rax + rax], dl
; X64-NEXT:    2e3: 00 4c 00 00 add byte ptr [rax + rax], cl
; X64-NEXT:    2e7: 00 44 00 00 add byte ptr [rax + rax], al
; X64-NEXT:    2eb: 00 0f add byte ptr [rdi], cl
; X64-NEXT:    2ed: 1f <unknown>
; X64-NEXT:    2ee: 40 00 83 ff 03 0f 84 add byte ptr [rbx - 0x7bf0fc01], al
;
; ARM64-LABEL: <switch_table3>:
; ARM64:         cmp w0, #0x3e9
; ARM64-NEXT:    b.eq <L4>
; ARM64-NEXT:    b.hi <L1>
; ARM64-NEXT:    sub w0, w0, #0x1
; ARM64-NEXT:    cmp w0, #0x5
; ARM64-NEXT:    b.hi <L3>
; ARM64-NEXT:    adrp x2, 0x0 <empty_switch>
; ARM64-NEXT:     R_AARCH64_ADR_PREL_PG_HI21
; ARM64-NEXT:    add x2, x2, #0x0
; ARM64-NEXT:     R_AARCH64_ADD_ABS_LO12_NC
; ARM64-NEXT:    ldrb w0, [x2, w0, uxtw #0]
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    adr x2, <L0>
; ARM64-NEXT:    add x2, x2, x0, lsl #2
; ARM64-NEXT:    br x2
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    sub w0, w0, #0x3ea
; ARM64-NEXT:    cmp w0, #0x4
; ARM64-NEXT:    b.hi <L3>
; ARM64-NEXT:    adrp x2, 0x0 <empty_switch>
; ARM64-NEXT:     R_AARCH64_ADR_PREL_PG_HI21
; ARM64-NEXT:    add x2, x2, #0x0
; ARM64-NEXT:     R_AARCH64_ADD_ABS_LO12_NC
; ARM64-NEXT:    ldrb w0, [x2, w0, uxtw #0]
; ARM64-NEXT:  <L2>:
; ARM64-NEXT:    adr x2, <L2>
; ARM64-NEXT:    add x2, x2, x0, lsl #2
; ARM64-NEXT:    br x2
; ARM64-NEXT:  <L3>:
; ARM64-NEXT:    b <L8>
; ARM64-NEXT:    b <L5>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L6>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L7>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L5>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L6>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L7>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:  <L4>:
; ARM64-NEXT:    b <L5>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L6>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L7>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L5>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L6>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L7>
; ARM64-NEXT:  <L5>:
; ARM64-NEXT:    mov x0, #0x3 // =3
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:  <L6>:
; ARM64-NEXT:    mov x0, #0x4 // =4
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:  <L7>:
; ARM64-NEXT:    mov x0, #0x5 // =5
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:  <L8>:
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:  <L9>:
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default [
    i32 1, label %eq3
    i32 2, label %eq4
    i32 3, label %eq5
    i32 4, label %eq3
    i32 5, label %eq4
    i32 6, label %eq5
    i32 1001, label %eq3
    i32 1002, label %eq4
    i32 1003, label %eq5
    i32 1004, label %eq3
    i32 1005, label %eq4
    i32 1006, label %eq5
  ]
eq3:
  ret i32 3
eq4:
  ret i32 4
eq5:
  ret i32 5
default:
  ret i32 -1
}


define i32 @switch_binsearch(i32 %0) {
; X64-LABEL: <switch_binsearch>:
; X64:         2f0: 83 ff 03 cmp edi, 0x3
; X64-NEXT:    2f3: 0f 84 4b 00 00 00 je <L4>
; X64-NEXT:    2f9: 0f 87 17 00 00 00 ja <L0>
; X64-NEXT:    2ff: 83 ff 01 cmp edi, 0x1
; X64-NEXT:    302: 0f 84 2c 00 00 00 je <L2>
; X64-NEXT:    308: 83 ff 02 cmp edi, 0x2
; X64-NEXT:    30b: 0f 84 2b 00 00 00 je <L3>
; X64-NEXT:    311: e9 17 00 00 00 jmp <L1>
; X64-NEXT:  <L0>:
; X64-NEXT:    316: 83 ff 64 cmp edi, 0x64
; X64-NEXT:    319: 0f 84 2d 00 00 00 je <L5>
; X64-NEXT:    31f: 83 ff 65 cmp edi, 0x65
; X64-NEXT:    322: 0f 84 2c 00 00 00 je <L6>
; X64-NEXT:    328: e9 00 00 00 00 jmp <L1>
; X64-NEXT:  <L1>:
; X64-NEXT:    32d: e9 59 00 00 00 jmp <L12>
; X64-NEXT:    332: 66 90 nop
; X64-NEXT:  <L2>:
; X64-NEXT:    334: e9 20 00 00 00 jmp <L7>
; X64-NEXT:    339: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L3>:
; X64-NEXT:    33c: e9 22 00 00 00 jmp <L8>
; X64-NEXT:    341: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L4>:
; X64-NEXT:    344: e9 24 00 00 00 jmp <L9>
; X64-NEXT:    349: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L5>:
; X64-NEXT:    34c: e9 26 00 00 00 jmp <L10>
; X64-NEXT:    351: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L6>:
; X64-NEXT:    354: e9 28 00 00 00 jmp <L11>
; X64-NEXT:  <L7>:
; X64-NEXT:    359: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    35e: e9 2d 00 00 00 jmp <L13>
; X64-NEXT:  <L8>:
; X64-NEXT:    363: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    368: e9 23 00 00 00 jmp <L13>
; X64-NEXT:  <L9>:
; X64-NEXT:    36d: b8 03 00 00 00 mov eax, 0x3
; X64-NEXT:    372: e9 19 00 00 00 jmp <L13>
; X64-NEXT:  <L10>:
; X64-NEXT:    377: b8 64 00 00 00 mov eax, 0x64
; X64-NEXT:    37c: e9 0f 00 00 00 jmp <L13>
; X64-NEXT:  <L11>:
; X64-NEXT:    381: b8 65 00 00 00 mov eax, 0x65
; X64-NEXT:    386: e9 05 00 00 00 jmp <L13>
; X64-NEXT:  <L12>:
; X64-NEXT:    38b: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:  <L13>:
; X64-NEXT:    390: c3 ret
; X64-NEXT:    391: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    39a: 66 0f 1f 44 00 00 nop word ptr [rax + rax]
;
; ARM64-LABEL: <switch_binsearch>:
; ARM64:         cmp w0, #0x3
; ARM64-NEXT:    b.eq <L4>
; ARM64-NEXT:    b.hi <L0>
; ARM64-NEXT:    cmp w0, #0x1
; ARM64-NEXT:    b.eq <L2>
; ARM64-NEXT:    cmp w0, #0x2
; ARM64-NEXT:    b.eq <L3>
; ARM64-NEXT:    b <L1>
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    cmp w0, #0x64
; ARM64-NEXT:    b.eq <L5>
; ARM64-NEXT:    cmp w0, #0x65
; ARM64-NEXT:    b.eq <L6>
; ARM64-NEXT:    b <L1>
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    b <L12>
; ARM64-NEXT:  <L2>:
; ARM64-NEXT:    b <L7>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:  <L3>:
; ARM64-NEXT:    b <L8>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:  <L4>:
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:  <L5>:
; ARM64-NEXT:    b <L10>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:  <L6>:
; ARM64-NEXT:    b <L11>
; ARM64-NEXT:  <L7>:
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    b <L13>
; ARM64-NEXT:  <L8>:
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    b <L13>
; ARM64-NEXT:  <L9>:
; ARM64-NEXT:    mov x0, #0x3 // =3
; ARM64-NEXT:    b <L13>
; ARM64-NEXT:  <L10>:
; ARM64-NEXT:    mov x0, #0x64 // =100
; ARM64-NEXT:    b <L13>
; ARM64-NEXT:  <L11>:
; ARM64-NEXT:    mov x0, #0x65 // =101
; ARM64-NEXT:    b <L13>
; ARM64-NEXT:  <L12>:
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:  <L13>:
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default [
    i32 1, label %eq1
    i32 2, label %eq2
    i32 3, label %eq3
    i32 100, label %eq100
    i32 101, label %eq101
  ]
eq1:
  ret i32 1
eq2:
  ret i32 2
eq3:
  ret i32 3
eq100:
  ret i32 100
eq101:
  ret i32 101
default:
  ret i32 -1
}

define i32 @switch_i32_noreuse(i32 %p) {
; X64-LABEL: <switch_i32_noreuse>:
; X64:         3a0: 55 push rbp
; X64-NEXT:    3a1: 48 89 e5 mov rbp, rsp
; X64-NEXT:    3a4: 53 push rbx
; X64-NEXT:    3a5: 89 fb mov ebx, edi
; X64-NEXT:    3a7: 89 d8 mov eax, ebx
; X64-NEXT:    3a9: 83 f8 01 cmp eax, 0x1
; X64-NEXT:    3ac: 0f 84 17 00 00 00 je <L1>
; X64-NEXT:    3b2: 83 f8 02 cmp eax, 0x2
; X64-NEXT:    3b5: 0f 84 16 00 00 00 je <L2>
; X64-NEXT:    3bb: e9 00 00 00 00 jmp <L0>
; X64-NEXT:  <L0>:
; X64-NEXT:    3c0: e9 25 00 00 00 jmp <L5>
; X64-NEXT:    3c5: 0f 1f 40 00 nop dword ptr [rax]
; X64-NEXT:  <L1>:
; X64-NEXT:    3c9: e9 08 00 00 00 jmp <L3>
; X64-NEXT:    3ce: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L2>:
; X64-NEXT:    3d1: e9 0a 00 00 00 jmp <L4>
; X64-NEXT:  <L3>:
; X64-NEXT:    3d6: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    3db: e9 0c 00 00 00 jmp <L6>
; X64-NEXT:  <L4>:
; X64-NEXT:    3e0: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    3e5: e9 02 00 00 00 jmp <L6>
; X64-NEXT:  <L5>:
; X64-NEXT:    3ea: 89 d8 mov eax, ebx
; X64-NEXT:  <L6>:
; X64-NEXT:    3ec: 5b pop rbx
; X64-NEXT:    3ed: 5d pop rbp
; X64-NEXT:    3ee: c3 ret
; X64-NEXT:    3ef: 90 nop
;
; ARM64-LABEL: <switch_i32_noreuse>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    str x19, [sp, #0x10]
; ARM64-NEXT:    mov w19, w0
; ARM64-NEXT:    mov w0, w19
; ARM64-NEXT:    cmp w0, #0x1
; ARM64-NEXT:    b.eq <L1>
; ARM64-NEXT:    cmp w0, #0x2
; ARM64-NEXT:    b.eq <L2>
; ARM64-NEXT:    b <L0>
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    b <L5>
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    b <L3>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:  <L2>:
; ARM64-NEXT:    b <L4>
; ARM64-NEXT:  <L3>:
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    b <L6>
; ARM64-NEXT:  <L4>:
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    b <L6>
; ARM64-NEXT:  <L5>:
; ARM64-NEXT:    mov w0, w19
; ARM64-NEXT:  <L6>:
; ARM64-NEXT:    ldr x19, [sp, #0x10]
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
  switch i32 %p, label %default [
    i32 1, label %l1
    i32 2, label %l2
  ]
l1:
  ret i32 1
l2:
  ret i32 2
default:
  ret i32 %p
}

define i64 @switch_i64_noreuse(i64 %p) {
; X64-LABEL: <switch_i64_noreuse>:
; X64:         3f0: 55 push rbp
; X64-NEXT:    3f1: 48 89 e5 mov rbp, rsp
; X64-NEXT:    3f4: 53 push rbx
; X64-NEXT:    3f5: 48 89 fb mov rbx, rdi
; X64-NEXT:    3f8: 48 89 d8 mov rax, rbx
; X64-NEXT:    3fb: 48 83 f8 01 cmp rax, 0x1
; X64-NEXT:    3ff: 0f 84 14 00 00 00 je <L1>
; X64-NEXT:    405: 48 83 f8 02 cmp rax, 0x2
; X64-NEXT:    409: 0f 84 12 00 00 00 je <L2>
; X64-NEXT:    40f: e9 00 00 00 00 jmp <L0>
; X64-NEXT:  <L0>:
; X64-NEXT:    414: e9 21 00 00 00 jmp <L5>
; X64-NEXT:  <L1>:
; X64-NEXT:    419: e9 08 00 00 00 jmp <L3>
; X64-NEXT:    41e: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L2>:
; X64-NEXT:    421: e9 0a 00 00 00 jmp <L4>
; X64-NEXT:  <L3>:
; X64-NEXT:    426: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    42b: e9 0d 00 00 00 jmp <L6>
; X64-NEXT:  <L4>:
; X64-NEXT:    430: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    435: e9 03 00 00 00 jmp <L6>
; X64-NEXT:  <L5>:
; X64-NEXT:    43a: 48 89 d8 mov rax, rbx
; X64-NEXT:  <L6>:
; X64-NEXT:    43d: 5b pop rbx
; X64-NEXT:    43e: 5d pop rbp
; X64-NEXT:    43f: c3 ret
;
; ARM64-LABEL: <switch_i64_noreuse>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    str x19, [sp, #0x10]
; ARM64-NEXT:    mov x19, x0
; ARM64-NEXT:    mov x0, x19
; ARM64-NEXT:    cmp x0, #0x1
; ARM64-NEXT:    b.eq <L1>
; ARM64-NEXT:    cmp x0, #0x2
; ARM64-NEXT:    b.eq <L2>
; ARM64-NEXT:    b <L0>
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    b <L5>
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    b <L3>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:  <L2>:
; ARM64-NEXT:    b <L4>
; ARM64-NEXT:  <L3>:
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    b <L6>
; ARM64-NEXT:  <L4>:
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    b <L6>
; ARM64-NEXT:  <L5>:
; ARM64-NEXT:    mov x0, x19
; ARM64-NEXT:  <L6>:
; ARM64-NEXT:    ldr x19, [sp, #0x10]
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
  switch i64 %p, label %default [
    i64 1, label %l1
    i64 2, label %l2
  ]
l1:
  ret i64 1
l2:
  ret i64 2
default:
  ret i64 %p
}

define i32 @switch_to_self() {
; X64-LABEL: <switch_to_self>:
; X64:       <L0>:
; X64-NEXT:    440: 31 c0 xor eax, eax
; X64-NEXT:    442: 83 f8 35 cmp eax, 0x35
; X64-NEXT:    445: 0f 84 99 00 00 00 je <L4>
; X64-NEXT:    44b: 0f 87 1e 00 00 00 ja <L1>
; X64-NEXT:    451: 83 e8 0a sub eax, 0xa
; X64-NEXT:    454: 83 f8 2a cmp eax, 0x2a
; X64-NEXT:    457: 0f 87 4f 00 00 00 ja <L3>
; X64-NEXT:    45d: 48 8d 15 c8 00 00 00 lea rdx, <switch_to_self+0xec>
; X64-NEXT:    464: 8b 04 82 mov eax, dword ptr [rdx + 4*rax]
; X64-NEXT:    467: 48 29 c2 sub rdx, rax
; X64-NEXT:    46a: ff e2 jmp rdx
; X64-NEXT:    46c: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L1>:
; X64-NEXT:    46f: 83 f8 62 cmp eax, 0x62
; X64-NEXT:    472: 0f 84 84 00 00 00 je <L7>
; X64-NEXT:    478: 0f 87 17 00 00 00 ja <L2>
; X64-NEXT:    47e: 83 f8 36 cmp eax, 0x36
; X64-NEXT:    481: 0f 84 65 00 00 00 je <L5>
; X64-NEXT:    487: 83 f8 37 cmp eax, 0x37
; X64-NEXT:    48a: 0f 84 64 00 00 00 je <L6>
; X64-NEXT:    490: e9 17 00 00 00 jmp <L3>
; X64-NEXT:  <L2>:
; X64-NEXT:    495: 83 f8 66 cmp eax, 0x66
; X64-NEXT:    498: 0f 84 66 00 00 00 je <L8>
; X64-NEXT:    49e: 83 f8 72 cmp eax, 0x72
; X64-NEXT:    4a1: 0f 84 65 00 00 00 je <L9>
; X64-NEXT:    4a7: e9 00 00 00 00 jmp <L3>
; X64-NEXT:  <L3>:
; X64-NEXT:    4ac: e9 75 00 00 00 jmp <L13>
; X64-NEXT:    4b1: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    4b4: eb 8a jmp <switch_to_self>
; X64-NEXT:    4b6: 66 0f 1f 44 00 00 nop word ptr [rax + rax]
; X64-NEXT:    4bc: e9 65 00 00 00 jmp <L13>
; X64-NEXT:    4c1: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    4c4: e9 5d 00 00 00 jmp <L13>
; X64-NEXT:    4c9: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    4cc: e9 55 00 00 00 jmp <L13>
; X64-NEXT:    4d1: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    4d4: e9 4d 00 00 00 jmp <L13>
; X64-NEXT:    4d9: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    4dc: e9 45 00 00 00 jmp <L13>
; X64-NEXT:    4e1: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L4>:
; X64-NEXT:    4e4: e9 3d 00 00 00 jmp <L13>
; X64-NEXT:    4e9: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L5>:
; X64-NEXT:    4ec: e9 35 00 00 00 jmp <L13>
; X64-NEXT:    4f1: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L6>:
; X64-NEXT:    4f4: e9 2d 00 00 00 jmp <L13>
; X64-NEXT:    4f9: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L7>:
; X64-NEXT:    4fc: e9 17 00 00 00 jmp <L11>
; X64-NEXT:    501: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L8>:
; X64-NEXT:    504: e9 16 00 00 00 jmp <L12>
; X64-NEXT:    509: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L9>:
; X64-NEXT:    50c: e9 00 00 00 00 jmp <L10>
; X64-NEXT:  <L10>:
; X64-NEXT:    511: 31 c0 xor eax, eax
; X64-NEXT:    513: e9 10 00 00 00 jmp <L14>
; X64-NEXT:  <L11>:
; X64-NEXT:    518: 31 c0 xor eax, eax
; X64-NEXT:    51a: e9 09 00 00 00 jmp <L14>
; X64-NEXT:  <L12>:
; X64-NEXT:    51f: 31 c0 xor eax, eax
; X64-NEXT:    521: e9 02 00 00 00 jmp <L14>
; X64-NEXT:  <L13>:
; X64-NEXT:    526: 31 c0 xor eax, eax
; X64-NEXT:  <L14>:
; X64-NEXT:    528: c3 ret
; X64-NEXT:    529: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    52c: 78 00 js <L15>
; X64-NEXT:  <L15>:
; X64-NEXT:    52e: 00 00 add byte ptr [rax], al
; X64-NEXT:    530: 80 00 00 add byte ptr [rax], 0x0
; X64-NEXT:    533: 00 80 00 00 00 80 add byte ptr [rax - 0x80000000], al
; X64-NEXT:    539: 00 00 add byte ptr [rax], al
; X64-NEXT:    53b: 00 80 00 00 00 80 add byte ptr [rax - 0x80000000], al
; X64-NEXT:    541: 00 00 add byte ptr [rax], al
; X64-NEXT:    543: 00 80 00 00 00 80 add byte ptr [rax - 0x80000000], al
; X64-NEXT:    549: 00 00 add byte ptr [rax], al
; X64-NEXT:    54b: 00 80 00 00 00 80 add byte ptr [rax - 0x80000000], al
; X64-NEXT:    551: 00 00 add byte ptr [rax], al
; X64-NEXT:    553: 00 80 00 00 00 80 add byte ptr [rax - 0x80000000], al
; X64-NEXT:    559: 00 00 add byte ptr [rax], al
; X64-NEXT:    55b: 00 80 00 00 00 80 add byte ptr [rax - 0x80000000], al
; X64-NEXT:    561: 00 00 add byte ptr [rax], al
; X64-NEXT:    563: 00 80 00 00 00 80 add byte ptr [rax - 0x80000000], al
; X64-NEXT:    569: 00 00 add byte ptr [rax], al
; X64-NEXT:    56b: 00 80 00 00 00 80 add byte ptr [rax - 0x80000000], al
; X64-NEXT:    571: 00 00 add byte ptr [rax], al
; X64-NEXT:    573: 00 80 00 00 00 80 add byte ptr [rax - 0x80000000], al
; X64-NEXT:    579: 00 00 add byte ptr [rax], al
; X64-NEXT:    57b: 00 80 00 00 00 80 add byte ptr [rax - 0x80000000], al
; X64-NEXT:    581: 00 00 add byte ptr [rax], al
; X64-NEXT:    583: 00 80 00 00 00 80 add byte ptr [rax - 0x80000000], al
; X64-NEXT:    589: 00 00 add byte ptr [rax], al
; X64-NEXT:    58b: 00 80 00 00 00 80 add byte ptr [rax - 0x80000000], al
; X64-NEXT:    591: 00 00 add byte ptr [rax], al
; X64-NEXT:    593: 00 80 00 00 00 80 add byte ptr [rax - 0x80000000], al
; X64-NEXT:    599: 00 00 add byte ptr [rax], al
; X64-NEXT:    59b: 00 80 00 00 00 80 add byte ptr [rax - 0x80000000], al
; X64-NEXT:    5a1: 00 00 add byte ptr [rax], al
; X64-NEXT:    5a3: 00 80 00 00 00 80 add byte ptr [rax - 0x80000000], al
; X64-NEXT:    5a9: 00 00 add byte ptr [rax], al
; X64-NEXT:    5ab: 00 80 00 00 00 80 add byte ptr [rax - 0x80000000], al
; X64-NEXT:    5b1: 00 00 add byte ptr [rax], al
; X64-NEXT:    5b3: 00 80 00 00 00 80 add byte ptr [rax - 0x80000000], al
; X64-NEXT:    5b9: 00 00 add byte ptr [rax], al
; X64-NEXT:    5bb: 00 80 00 00 00 80 add byte ptr [rax - 0x80000000], al
; X64-NEXT:    5c1: 00 00 add byte ptr [rax], al
; X64-NEXT:    5c3: 00 70 00 add byte ptr [rax], dh
; X64-NEXT:    5c6: 00 00 add byte ptr [rax], al
; X64-NEXT:    5c8: 68 00 00 00 60 push 0x60000000
; X64-NEXT:    5cd: 00 00 add byte ptr [rax], al
; X64-NEXT:    5cf: 00 58 00 add byte ptr [rax], bl
; X64-NEXT:    5d2: 00 00 add byte ptr [rax], al
; X64-NEXT:    5d4: 50 push rax
; X64-NEXT:    5d5: 00 00 add byte ptr [rax], al
; X64-NEXT:    5d7: 00 <unknown>
;
; ARM64-LABEL: <switch_to_self>:
; ARM64:       <L0>:
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    cmp w0, #0x35
; ARM64-NEXT:    b.eq <L5>
; ARM64-NEXT:    b.hi <L2>
; ARM64-NEXT:    sub w0, w0, #0xa
; ARM64-NEXT:    cmp w0, #0x2a
; ARM64-NEXT:    b.hi <L4>
; ARM64-NEXT:    adrp x2, 0x0 <empty_switch>
; ARM64-NEXT:     R_AARCH64_ADR_PREL_PG_HI21
; ARM64-NEXT:    add x2, x2, #0x0
; ARM64-NEXT:     R_AARCH64_ADD_ABS_LO12_NC
; ARM64-NEXT:    ldrb w0, [x2, w0, uxtw #0]
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    adr x2, <L1>
; ARM64-NEXT:    add x2, x2, x0, lsl #2
; ARM64-NEXT:    br x2
; ARM64-NEXT:  <L2>:
; ARM64-NEXT:    cmp w0, #0x62
; ARM64-NEXT:    b.eq <L8>
; ARM64-NEXT:    b.hi <L3>
; ARM64-NEXT:    cmp w0, #0x36
; ARM64-NEXT:    b.eq <L6>
; ARM64-NEXT:    cmp w0, #0x37
; ARM64-NEXT:    b.eq <L7>
; ARM64-NEXT:    b <L4>
; ARM64-NEXT:  <L3>:
; ARM64-NEXT:    cmp w0, #0x66
; ARM64-NEXT:    b.eq <L9>
; ARM64-NEXT:    cmp w0, #0x72
; ARM64-NEXT:    b.eq <L10>
; ARM64-NEXT:    b <L4>
; ARM64-NEXT:  <L4>:
; ARM64-NEXT:    b <L14>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <switch_to_self>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L14>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L14>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L14>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L14>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:    b <L14>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:  <L5>:
; ARM64-NEXT:    b <L14>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:  <L6>:
; ARM64-NEXT:    b <L14>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:  <L7>:
; ARM64-NEXT:    b <L14>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:  <L8>:
; ARM64-NEXT:    b <L12>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:  <L9>:
; ARM64-NEXT:    b <L13>
; ARM64-NEXT:    udf #0x0
; ARM64-NEXT:  <L10>:
; ARM64-NEXT:    b <L11>
; ARM64-NEXT:  <L11>:
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    b <L15>
; ARM64-NEXT:  <L12>:
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    b <L15>
; ARM64-NEXT:  <L13>:
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    b <L15>
; ARM64-NEXT:  <L14>:
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:  <L15>:
; ARM64-NEXT:    ret
  br label %1

1:
  switch i32 0, label %5 [
    i32 55, label %5
    i32 114, label %2
    i32 54, label %5
    i32 98, label %3
    i32 102, label %4
    i32 10, label %1
    i32 48, label %5
    i32 49, label %5
    i32 50, label %5
    i32 51, label %5
    i32 52, label %5
    i32 53, label %5
  ]

2:
  ret i32 0

3:
  ret i32 0

4:
  ret i32 0

5:
  ret i32 0
}
