; NOTE: Assertions have been autogenerated by test/update_tpde_llc_test_checks.py UTC_ARGS: --version 5
; SPDX-FileCopyrightText: 2025 Contributors to TPDE <https://tpde.org>
;
; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

; RUN: tpde-llc --target=x86_64 %s | llvm-objdump -d -r --symbolize-operands --x86-asm-syntax=intel - | FileCheck %s -check-prefixes=X64
; RUN: tpde-llc --target=aarch64 %s | %objdump | FileCheck %s -check-prefixes=ARM64
; XFAIL: llvm19.1
; XFAIL: llvm20.1

define i32 @empty_switch(i32 %0) {
; X64-LABEL: <empty_switch>:
; X64:         0: e9 00 00 00 00 jmp <L0>
; X64-NEXT:  <L0>:
; X64-NEXT:    5: e9 00 00 00 00 jmp <L1>
; X64-NEXT:  <L1>:
; X64-NEXT:    a: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:    f: c3 ret
;
; ARM64-LABEL: <empty_switch>:
; ARM64:         b <L0>
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    b <L1>
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default []
default:
  ret i32 -1
}

define i32 @basic_switch(i32 %0) {
; X64-LABEL: <basic_switch>:
; X64:         10: 83 ff 00 cmp edi, 0x0
; X64-NEXT:    13: 0f 84 1c 00 00 00 je <L1>
; X64-NEXT:    19: 83 ff 01 cmp edi, 0x1
; X64-NEXT:    1c: 0f 84 1a 00 00 00 je <L2>
; X64-NEXT:    22: 83 ff 02 cmp edi, 0x2
; X64-NEXT:    25: 0f 84 1b 00 00 00 je <L3>
; X64-NEXT:    2b: e9 00 00 00 00 jmp <L0>
; X64-NEXT:  <L0>:
; X64-NEXT:    30: e9 1b 00 00 00 jmp <L4>
; X64-NEXT:  <L1>:
; X64-NEXT:    35: 31 c0 xor eax, eax
; X64-NEXT:    37: e9 19 00 00 00 jmp <L5>
; X64-NEXT:  <L2>:
; X64-NEXT:    3c: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    41: e9 0f 00 00 00 jmp <L5>
; X64-NEXT:  <L3>:
; X64-NEXT:    46: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    4b: e9 05 00 00 00 jmp <L5>
; X64-NEXT:  <L4>:
; X64-NEXT:    50: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:  <L5>:
; X64-NEXT:    55: c3 ret
; X64-NEXT:    56: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    5f: 90 nop
;
; ARM64-LABEL: <basic_switch>:
; ARM64:         cmp w0, #0x0
; ARM64-NEXT:    b.eq <L1>
; ARM64-NEXT:    cmp w0, #0x1
; ARM64-NEXT:    b.eq <L2>
; ARM64-NEXT:    cmp w0, #0x2
; ARM64-NEXT:    b.eq <L3>
; ARM64-NEXT:    b <L0>
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    b <L4>
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    b <L5>
; ARM64-NEXT:  <L2>:
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    b <L5>
; ARM64-NEXT:  <L3>:
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    b <L5>
; ARM64-NEXT:  <L4>:
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:  <L5>:
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default [ i32 0, label %eq0
                                  i32 1, label %eq1
                                  i32 2, label %eq2]
eq0:
  ret i32 0
eq1:
  ret i32 1
eq2:
  ret i32 2
default:
  ret i32 -1
}

define i32 @switch_table(i32 %0) {
; x64-label: switch_table>:
; x64:    b0: 55 push rbp
; x64:    b1: 48 89 e5 mov rbp, rsp
; x64:    b4: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; x64:    bd: 48 81 ec 10 00 00 00 sub rsp, 0x10
; x64:    c4: 83 ff 06 cmp edi, 0x6
; x64:    c7: 0f 87 2f 00 00 00 ja <l0>
; x64:    cd: 89 ff mov edi, edi
; x64:    cf: 48 8d 05 0a 00 00 00 lea rax, <switch_table+0x30>
; x64:    d6: 48 63 3c b8 movsxd rdi, dword ptr [rax + 4*rdi]
; x64:    da: 48 01 f8 add rax, rdi
; x64:    dd: ff e0 jmp rax
; x64:    df: 00 21 add byte ptr [rcx], ah
; x64:    e1: 00 00 add byte ptr [rax], al
; x64:    e3: 00 26 add byte ptr [rsi], ah
; x64:    e5: 00 00 add byte ptr [rax], al
; x64:    e7: 00 2b add byte ptr [rbx], ch
; x64:    e9: 00 00 add byte ptr [rax], al
; x64:    eb: 00 1c 00 add byte ptr [rax + rax], bl
; x64:    ee: 00 00 add byte ptr [rax], al
; x64:    f0: 30 00 xor byte ptr [rax], al
; x64:    f2: 00 00 add byte ptr [rax], al
; x64:    f4: 35 00 00 00 3a xor eax, 0x3a000000
; x64:    f9: 00 00 add byte ptr [rax], al
; x64:    fb: 00 e9 add cl, ch
; x64:    fd: a8 00 test al, 0x0
; x64:    ff: 00 00 add byte ptr [rax], al
; x64:    101: e9 19 00 00 00 jmp <l1>
; x64:    106: e9 2b 00 00 00 jmp <l2>
; x64:    10b: e9 3d 00 00 00 jmp <l3>
; x64:    110: e9 4f 00 00 00 jmp <l4>
; x64:    115: e9 61 00 00 00 jmp <l5>
; x64:    11a: e9 73 00 00 00 jmp <l6>
; x64:  <l1>:
; x64:    11f: b8 00 00 00 00 mov eax, 0x0
; x64:    124: 48 83 c4 10 add rsp, 0x10
; x64:    128: 5d pop rbp
; x64:    129: c3 ret
; x64:  <l2>:
; x64:    136: b8 01 00 00 00 mov eax, 0x1
; x64:    13b: 48 83 c4 10 add rsp, 0x10
; x64:    13f: 5d pop rbp
; x64:    140: c3 ret
; x64:  <l3>:
; x64:    14d: b8 02 00 00 00 mov eax, 0x2
; x64:    152: 48 83 c4 10 add rsp, 0x10
; x64:    156: 5d pop rbp
; x64:    157: c3 ret
; x64:  <l4>:
; x64:    164: b8 04 00 00 00 mov eax, 0x4
; x64:    169: 48 83 c4 10 add rsp, 0x10
; x64:    16d: 5d pop rbp
; x64:    16e: c3 ret
; x64:  <l5>:
; x64:    17b: b8 05 00 00 00 mov eax, 0x5
; x64:    180: 48 83 c4 10 add rsp, 0x10
; x64:    184: 5d pop rbp
; x64:    185: c3 ret
; x64:  <l6>:
; x64:    192: b8 06 00 00 00 mov eax, 0x6
; x64:    197: 48 83 c4 10 add rsp, 0x10
; x64:    19b: 5d pop rbp
; x64:    19c: c3 ret
; x64:    1a9: b8 ff ff ff ff mov eax, 0xffffffff
; x64:    1ae: 48 83 c4 10 add rsp, 0x10
; x64:    1b2: 5d pop rbp
; x64:    1b3: c3 ret
; x64:     ...
; X64-LABEL: <switch_table>:
; X64:         60: 83 ff 06 cmp edi, 0x6
; X64-NEXT:    63: 0f 87 14 00 00 00 ja <L0>
; X64-NEXT:    69: 89 ff mov edi, edi
; X64-NEXT:    6b: 48 8d 05 52 00 00 00 lea rax, <switch_table+0x64>
; X64-NEXT:    72: 8b 3c b8 mov edi, dword ptr [rax + 4*rdi]
; X64-NEXT:    75: 48 29 f8 sub rax, rdi
; X64-NEXT:    78: ff e0 jmp rax
; X64-NEXT:    7a: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L0>:
; X64-NEXT:    7d: e9 39 00 00 00 jmp <L1>
; X64-NEXT:    82: 31 c0 xor eax, eax
; X64-NEXT:    84: e9 37 00 00 00 jmp <L2>
; X64-NEXT:    89: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    8e: e9 2d 00 00 00 jmp <L2>
; X64-NEXT:    93: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    98: e9 23 00 00 00 jmp <L2>
; X64-NEXT:    9d: b8 04 00 00 00 mov eax, 0x4
; X64-NEXT:    a2: e9 19 00 00 00 jmp <L2>
; X64-NEXT:    a7: b8 05 00 00 00 mov eax, 0x5
; X64-NEXT:    ac: e9 0f 00 00 00 jmp <L2>
; X64-NEXT:    b1: b8 06 00 00 00 mov eax, 0x6
; X64-NEXT:    b6: e9 05 00 00 00 jmp <L2>
; X64-NEXT:  <L1>:
; X64-NEXT:    bb: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:  <L2>:
; X64-NEXT:    c0: c3 ret
; X64-NEXT:    c1: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    c4: 42 00 00 add byte ptr [rax], al
; X64-NEXT:    c7: 00 3b add byte ptr [rbx], bh
; X64-NEXT:    c9: 00 00 add byte ptr [rax], al
; X64-NEXT:    cb: 00 31 add byte ptr [rcx], dh
; X64-NEXT:    cd: 00 00 add byte ptr [rax], al
; X64-NEXT:    cf: 00 47 00 add byte ptr [rdi], al
; X64-NEXT:    d2: 00 00 add byte ptr [rax], al
; X64-NEXT:    d4: 27 <unknown>
; X64-NEXT:    d5: 00 00 add byte ptr [rax], al
; X64-NEXT:    d7: 00 1d 00 00 00 13 add byte ptr , bl <switch_to_self+0x12fffd1d>
; X64-NEXT:    dd: 00 00 add byte ptr [rax], al
; X64-NEXT:    df: 00 83 ef 03 83 ff add byte ptr [rbx - 0x7cfc11], al
;
; ARM64-LABEL: <switch_table>:
; ARM64:         cmp w0, #0x6
; ARM64-NEXT:    b.hi <L1>
; ARM64-NEXT:    adrp x1, 0x0 <empty_switch>
; ARM64-NEXT:     R_AARCH64_ADR_PREL_PG_HI21
; ARM64-NEXT:    add x1, x1, #0x0
; ARM64-NEXT:     R_AARCH64_ADD_ABS_LO12_NC
; ARM64-NEXT:    ldrb w0, [x1, w0, uxtw #0]
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    adr x1, <L0>
; ARM64-NEXT:    add x1, x1, x0, lsl #2
; ARM64-NEXT:    br x1
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    b <L2>
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    b <L3>
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    b <L3>
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    b <L3>
; ARM64-NEXT:    mov x0, #0x4 // =4
; ARM64-NEXT:    b <L3>
; ARM64-NEXT:    mov x0, #0x5 // =5
; ARM64-NEXT:    b <L3>
; ARM64-NEXT:    mov x0, #0x6 // =6
; ARM64-NEXT:    b <L3>
; ARM64-NEXT:  <L2>:
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:  <L3>:
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default [
    i32 0, label %eq0
    i32 1, label %eq1
    i32 2, label %eq2
    i32 4, label %eq4
    i32 5, label %eq5
    i32 6, label %eq6]
eq0:
  ret i32 0
eq1:
  ret i32 1
eq2:
  ret i32 2
eq4:
  ret i32 4
eq5:
  ret i32 5
eq6:
  ret i32 6
default:
  ret i32 -1
}

define i32 @switch_table2(i32 %0) {
; X64-LABEL: <switch_table2>:
; X64:         e0: 83 ef 03 sub edi, 0x3
; X64-NEXT:    e3: 83 ff 06 cmp edi, 0x6
; X64-NEXT:    e6: 0f 87 12 00 00 00 ja <L0>
; X64-NEXT:    ec: 48 8d 05 55 00 00 00 lea rax, <switch_table2+0x68>
; X64-NEXT:    f3: 8b 3c b8 mov edi, dword ptr [rax + 4*rdi]
; X64-NEXT:    f6: 48 29 f8 sub rax, rdi
; X64-NEXT:    f9: ff e0 jmp rax
; X64-NEXT:    fb: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L0>:
; X64-NEXT:    fe: e9 3c 00 00 00 jmp <L1>
; X64-NEXT:    103: b8 03 00 00 00 mov eax, 0x3
; X64-NEXT:    108: e9 37 00 00 00 jmp <L2>
; X64-NEXT:    10d: b8 04 00 00 00 mov eax, 0x4
; X64-NEXT:    112: e9 2d 00 00 00 jmp <L2>
; X64-NEXT:    117: b8 05 00 00 00 mov eax, 0x5
; X64-NEXT:    11c: e9 23 00 00 00 jmp <L2>
; X64-NEXT:    121: b8 07 00 00 00 mov eax, 0x7
; X64-NEXT:    126: e9 19 00 00 00 jmp <L2>
; X64-NEXT:    12b: b8 08 00 00 00 mov eax, 0x8
; X64-NEXT:    130: e9 0f 00 00 00 jmp <L2>
; X64-NEXT:    135: b8 09 00 00 00 mov eax, 0x9
; X64-NEXT:    13a: e9 05 00 00 00 jmp <L2>
; X64-NEXT:  <L1>:
; X64-NEXT:    13f: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:  <L2>:
; X64-NEXT:    144: c3 ret
; X64-NEXT:    145: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    148: 45 00 00 add byte ptr [r8], r8b
; X64-NEXT:    14b: 00 3b add byte ptr [rbx], bh
; X64-NEXT:    14d: 00 00 add byte ptr [rax], al
; X64-NEXT:    14f: 00 31 add byte ptr [rcx], dh
; X64-NEXT:    151: 00 00 add byte ptr [rax], al
; X64-NEXT:    153: 00 4a 00 add byte ptr [rdx], cl
; X64-NEXT:    156: 00 00 add byte ptr [rax], al
; X64-NEXT:    158: 27 <unknown>
; X64-NEXT:    159: 00 00 add byte ptr [rax], al
; X64-NEXT:    15b: 00 1d 00 00 00 13 add byte ptr , bl <switch_to_self+0x12fffda1>
; X64-NEXT:    161: 00 00 add byte ptr [rax], al
; X64-NEXT:    163: 00 66 0f add byte ptr [rsi + 0xf], ah
; X64-NEXT:    166: 1f <unknown>
; X64-NEXT:    167: 84 00 test byte ptr [rax], al
; X64-NEXT:    169: 00 00 add byte ptr [rax], al
; X64-NEXT:    16b: 00 00 add byte ptr [rax], al
; X64-NEXT:    16d: 0f 1f 00 nop dword ptr [rax]
;
; ARM64-LABEL: <switch_table2>:
; ARM64:         sub w0, w0, #0x3
; ARM64-NEXT:    cmp w0, #0x6
; ARM64-NEXT:    b.hi <L1>
; ARM64-NEXT:    adrp x1, 0x0 <empty_switch>
; ARM64-NEXT:     R_AARCH64_ADR_PREL_PG_HI21
; ARM64-NEXT:    add x1, x1, #0x0
; ARM64-NEXT:     R_AARCH64_ADD_ABS_LO12_NC
; ARM64-NEXT:    ldrb w0, [x1, w0, uxtw #0]
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    adr x1, <L0>
; ARM64-NEXT:    add x1, x1, x0, lsl #2
; ARM64-NEXT:    br x1
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    b <L2>
; ARM64-NEXT:    mov x0, #0x3 // =3
; ARM64-NEXT:    b <L3>
; ARM64-NEXT:    mov x0, #0x4 // =4
; ARM64-NEXT:    b <L3>
; ARM64-NEXT:    mov x0, #0x5 // =5
; ARM64-NEXT:    b <L3>
; ARM64-NEXT:    mov x0, #0x7 // =7
; ARM64-NEXT:    b <L3>
; ARM64-NEXT:    mov x0, #0x8 // =8
; ARM64-NEXT:    b <L3>
; ARM64-NEXT:    mov x0, #0x9 // =9
; ARM64-NEXT:    b <L3>
; ARM64-NEXT:  <L2>:
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:  <L3>:
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default [
    i32 3, label %eq3
    i32 4, label %eq4
    i32 5, label %eq5
    i32 7, label %eq7
    i32 8, label %eq8
    i32 9, label %eq9]
eq3:
  ret i32 3
eq4:
  ret i32 4
eq5:
  ret i32 5
eq7:
  ret i32 7
eq8:
  ret i32 8
eq9:
  ret i32 9
default:
  ret i32 -1
}

define i32 @switch_table3(i32 %0) {
; X64-LABEL: <switch_table3>:
; X64:         170: 81 ff e9 03 00 00 cmp edi, 0x3e9
; X64-NEXT:    176: 0f 84 80 00 00 00 je <L2>
; X64-NEXT:    17c: 0f 87 1e 00 00 00 ja <L0>
; X64-NEXT:    182: 83 ef 01 sub edi, 0x1
; X64-NEXT:    185: 83 ff 05 cmp edi, 0x5
; X64-NEXT:    188: 0f 87 33 00 00 00 ja <L1>
; X64-NEXT:    18e: 48 8d 05 e3 00 00 00 lea rax, <switch_table3+0x108>
; X64-NEXT:    195: 8b 3c b8 mov edi, dword ptr [rax + 4*rdi]
; X64-NEXT:    198: 48 29 f8 sub rax, rdi
; X64-NEXT:    19b: ff e0 jmp rax
; X64-NEXT:    19d: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L0>:
; X64-NEXT:    1a0: 81 ef ea 03 00 00 sub edi, 0x3ea
; X64-NEXT:    1a6: 83 ff 04 cmp edi, 0x4
; X64-NEXT:    1a9: 0f 87 12 00 00 00 ja <L1>
; X64-NEXT:    1af: 48 8d 05 da 00 00 00 lea rax, <switch_table3+0x120>
; X64-NEXT:    1b6: 8b 3c b8 mov edi, dword ptr [rax + 4*rdi]
; X64-NEXT:    1b9: 48 29 f8 sub rax, rdi
; X64-NEXT:    1bc: ff e0 jmp rax
; X64-NEXT:    1be: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L1>:
; X64-NEXT:    1c1: e9 a9 00 00 00 jmp <L6>
; X64-NEXT:    1c6: 66 0f 1f 44 00 00 nop word ptr [rax + rax]
; X64-NEXT:    1cc: e9 80 00 00 00 jmp <L3>
; X64-NEXT:    1d1: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    1da: 66 90 nop
; X64-NEXT:    1dc: e9 7a 00 00 00 jmp <L4>
; X64-NEXT:    1e1: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    1ea: 66 90 nop
; X64-NEXT:    1ec: e9 74 00 00 00 jmp <L5>
; X64-NEXT:    1f1: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    1fa: 66 90 nop
; X64-NEXT:  <L2>:
; X64-NEXT:    1fc: e9 50 00 00 00 jmp <L3>
; X64-NEXT:    201: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    20a: 66 90 nop
; X64-NEXT:    20c: e9 4a 00 00 00 jmp <L4>
; X64-NEXT:    211: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    21a: 66 90 nop
; X64-NEXT:    21c: e9 44 00 00 00 jmp <L5>
; X64-NEXT:    221: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    22a: 66 90 nop
; X64-NEXT:    22c: e9 20 00 00 00 jmp <L3>
; X64-NEXT:    231: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    23a: 66 90 nop
; X64-NEXT:    23c: e9 1a 00 00 00 jmp <L4>
; X64-NEXT:    241: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    24a: 66 90 nop
; X64-NEXT:    24c: e9 14 00 00 00 jmp <L5>
; X64-NEXT:  <L3>:
; X64-NEXT:    251: b8 03 00 00 00 mov eax, 0x3
; X64-NEXT:    256: e9 19 00 00 00 jmp <L7>
; X64-NEXT:  <L4>:
; X64-NEXT:    25b: b8 04 00 00 00 mov eax, 0x4
; X64-NEXT:    260: e9 0f 00 00 00 jmp <L7>
; X64-NEXT:  <L5>:
; X64-NEXT:    265: b8 05 00 00 00 mov eax, 0x5
; X64-NEXT:    26a: e9 05 00 00 00 jmp <L7>
; X64-NEXT:  <L6>:
; X64-NEXT:    26f: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:  <L7>:
; X64-NEXT:    274: c3 ret
; X64-NEXT:    275: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    278: 27 <unknown>
; X64-NEXT:    279: 00 00 add byte ptr [rax], al
; X64-NEXT:    27b: 00 1d 00 00 00 13 add byte ptr , bl <switch_to_self+0x12fffec1>
; X64-NEXT:    281: 00 00 add byte ptr [rax], al
; X64-NEXT:    283: 00 ac 00 00 00 9c 00 add byte ptr [rax + rax + 0x9c0000], ch
; X64-NEXT:    28a: 00 00 add byte ptr [rax], al
; X64-NEXT:    28c: 8c 00 mov word ptr [rax], es
; X64-NEXT:    28e: 00 00 add byte ptr [rax], al
; X64-NEXT:    290: 84 00 test byte ptr [rax], al
; X64-NEXT:    292: 00 00 add byte ptr [rax], al
; X64-NEXT:    294: 74 00 je <L8>
; X64-NEXT:  <L8>:
; X64-NEXT:    296: 00 00 add byte ptr [rax], al
; X64-NEXT:    298: 64 00 00 add byte ptr fs:[rax], al
; X64-NEXT:    29b: 00 54 00 00 add byte ptr [rax + rax], dl
; X64-NEXT:    29f: 00 44 00 00 add byte ptr [rax + rax], al
; X64-NEXT:    2a3: 00 66 0f add byte ptr [rsi + 0xf], ah
; X64-NEXT:    2a6: 1f <unknown>
; X64-NEXT:    2a7: 84 00 test byte ptr [rax], al
; X64-NEXT:    2a9: 00 00 add byte ptr [rax], al
; X64-NEXT:    2ab: 00 00 add byte ptr [rax], al
; X64-NEXT:    2ad: 0f 1f 00 nop dword ptr [rax]
;
; ARM64-LABEL: <switch_table3>:
; ARM64:         cmp w0, #0x3e9
; ARM64-NEXT:    b.eq <L4>
; ARM64-NEXT:    b.hi <L1>
; ARM64-NEXT:    sub w0, w0, #0x1
; ARM64-NEXT:    cmp w0, #0x5
; ARM64-NEXT:    b.hi <L3>
; ARM64-NEXT:    adrp x1, 0x0 <empty_switch>
; ARM64-NEXT:     R_AARCH64_ADR_PREL_PG_HI21
; ARM64-NEXT:    add x1, x1, #0x0
; ARM64-NEXT:     R_AARCH64_ADD_ABS_LO12_NC
; ARM64-NEXT:    ldrb w0, [x1, w0, uxtw #0]
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    adr x1, <L0>
; ARM64-NEXT:    add x1, x1, x0, lsl #2
; ARM64-NEXT:    br x1
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    sub w0, w0, #0x3ea
; ARM64-NEXT:    cmp w0, #0x4
; ARM64-NEXT:    b.hi <L3>
; ARM64-NEXT:    adrp x1, 0x0 <empty_switch>
; ARM64-NEXT:     R_AARCH64_ADR_PREL_PG_HI21
; ARM64-NEXT:    add x1, x1, #0x0
; ARM64-NEXT:     R_AARCH64_ADD_ABS_LO12_NC
; ARM64-NEXT:    ldrb w0, [x1, w0, uxtw #0]
; ARM64-NEXT:  <L2>:
; ARM64-NEXT:    adr x1, <L2>
; ARM64-NEXT:    add x1, x1, x0, lsl #2
; ARM64-NEXT:    br x1
; ARM64-NEXT:  <L3>:
; ARM64-NEXT:    b <L8>
; ARM64-NEXT:     ...
; ARM64-NEXT:    b <L5>
; ARM64-NEXT:     ...
; ARM64-NEXT:    b <L6>
; ARM64-NEXT:     ...
; ARM64-NEXT:    b <L7>
; ARM64-NEXT:     ...
; ARM64-NEXT:  <L4>:
; ARM64-NEXT:    b <L5>
; ARM64-NEXT:     ...
; ARM64-NEXT:    b <L6>
; ARM64-NEXT:     ...
; ARM64-NEXT:    b <L7>
; ARM64-NEXT:     ...
; ARM64-NEXT:    b <L5>
; ARM64-NEXT:     ...
; ARM64-NEXT:    b <L6>
; ARM64-NEXT:     ...
; ARM64-NEXT:    b <L7>
; ARM64-NEXT:  <L5>:
; ARM64-NEXT:    mov x0, #0x3 // =3
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:  <L6>:
; ARM64-NEXT:    mov x0, #0x4 // =4
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:  <L7>:
; ARM64-NEXT:    mov x0, #0x5 // =5
; ARM64-NEXT:    b <L9>
; ARM64-NEXT:  <L8>:
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:  <L9>:
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default [
    i32 1, label %eq3
    i32 2, label %eq4
    i32 3, label %eq5
    i32 4, label %eq3
    i32 5, label %eq4
    i32 6, label %eq5
    i32 1001, label %eq3
    i32 1002, label %eq4
    i32 1003, label %eq5
    i32 1004, label %eq3
    i32 1005, label %eq4
    i32 1006, label %eq5
  ]
eq3:
  ret i32 3
eq4:
  ret i32 4
eq5:
  ret i32 5
default:
  ret i32 -1
}


define i32 @switch_binsearch(i32 %0) {
; X64-LABEL: <switch_binsearch>:
; X64:         2b0: 83 ff 03 cmp edi, 0x3
; X64-NEXT:    2b3: 0f 84 4d 00 00 00 je <L4>
; X64-NEXT:    2b9: 0f 87 17 00 00 00 ja <L0>
; X64-NEXT:    2bf: 83 ff 01 cmp edi, 0x1
; X64-NEXT:    2c2: 0f 84 2a 00 00 00 je <L2>
; X64-NEXT:    2c8: 83 ff 02 cmp edi, 0x2
; X64-NEXT:    2cb: 0f 84 2b 00 00 00 je <L3>
; X64-NEXT:    2d1: e9 17 00 00 00 jmp <L1>
; X64-NEXT:  <L0>:
; X64-NEXT:    2d6: 83 ff 64 cmp edi, 0x64
; X64-NEXT:    2d9: 0f 84 31 00 00 00 je <L5>
; X64-NEXT:    2df: 83 ff 65 cmp edi, 0x65
; X64-NEXT:    2e2: 0f 84 32 00 00 00 je <L6>
; X64-NEXT:    2e8: e9 00 00 00 00 jmp <L1>
; X64-NEXT:  <L1>:
; X64-NEXT:    2ed: e9 32 00 00 00 jmp <L7>
; X64-NEXT:  <L2>:
; X64-NEXT:    2f2: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    2f7: e9 2d 00 00 00 jmp <L8>
; X64-NEXT:  <L3>:
; X64-NEXT:    2fc: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    301: e9 23 00 00 00 jmp <L8>
; X64-NEXT:  <L4>:
; X64-NEXT:    306: b8 03 00 00 00 mov eax, 0x3
; X64-NEXT:    30b: e9 19 00 00 00 jmp <L8>
; X64-NEXT:  <L5>:
; X64-NEXT:    310: b8 64 00 00 00 mov eax, 0x64
; X64-NEXT:    315: e9 0f 00 00 00 jmp <L8>
; X64-NEXT:  <L6>:
; X64-NEXT:    31a: b8 65 00 00 00 mov eax, 0x65
; X64-NEXT:    31f: e9 05 00 00 00 jmp <L8>
; X64-NEXT:  <L7>:
; X64-NEXT:    324: b8 ff ff ff ff mov eax, 0xffffffff
; X64-NEXT:  <L8>:
; X64-NEXT:    329: c3 ret
; X64-NEXT:    32a: 66 0f 1f 44 00 00 nop word ptr [rax + rax]
;
; ARM64-LABEL: <switch_binsearch>:
; ARM64:         cmp w0, #0x3
; ARM64-NEXT:    b.eq <L4>
; ARM64-NEXT:    b.hi <L0>
; ARM64-NEXT:    cmp w0, #0x1
; ARM64-NEXT:    b.eq <L2>
; ARM64-NEXT:    cmp w0, #0x2
; ARM64-NEXT:    b.eq <L3>
; ARM64-NEXT:    b <L1>
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    cmp w0, #0x64
; ARM64-NEXT:    b.eq <L5>
; ARM64-NEXT:    cmp w0, #0x65
; ARM64-NEXT:    b.eq <L6>
; ARM64-NEXT:    b <L1>
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    b <L7>
; ARM64-NEXT:  <L2>:
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    b <L8>
; ARM64-NEXT:  <L3>:
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    b <L8>
; ARM64-NEXT:  <L4>:
; ARM64-NEXT:    mov x0, #0x3 // =3
; ARM64-NEXT:    b <L8>
; ARM64-NEXT:  <L5>:
; ARM64-NEXT:    mov x0, #0x64 // =100
; ARM64-NEXT:    b <L8>
; ARM64-NEXT:  <L6>:
; ARM64-NEXT:    mov x0, #0x65 // =101
; ARM64-NEXT:    b <L8>
; ARM64-NEXT:  <L7>:
; ARM64-NEXT:    mov x0, #0xffffffff // =4294967295
; ARM64-NEXT:  <L8>:
; ARM64-NEXT:    ret
entry:
  switch i32 %0, label %default [
    i32 1, label %eq1
    i32 2, label %eq2
    i32 3, label %eq3
    i32 100, label %eq100
    i32 101, label %eq101
  ]
eq1:
  ret i32 1
eq2:
  ret i32 2
eq3:
  ret i32 3
eq100:
  ret i32 100
eq101:
  ret i32 101
default:
  ret i32 -1
}

define i32 @switch_i32_noreuse(i32 %p) {
; X64-LABEL: <switch_i32_noreuse>:
; X64:         330: 55 push rbp
; X64-NEXT:    331: 48 89 e5 mov rbp, rsp
; X64-NEXT:    334: 53 push rbx
; X64-NEXT:    335: 89 fb mov ebx, edi
; X64-NEXT:    337: 89 d8 mov eax, ebx
; X64-NEXT:    339: 83 f8 01 cmp eax, 0x1
; X64-NEXT:    33c: 0f 84 13 00 00 00 je <L1>
; X64-NEXT:    342: 83 f8 02 cmp eax, 0x2
; X64-NEXT:    345: 0f 84 14 00 00 00 je <L2>
; X64-NEXT:    34b: e9 00 00 00 00 jmp <L0>
; X64-NEXT:  <L0>:
; X64-NEXT:    350: e9 14 00 00 00 jmp <L3>
; X64-NEXT:  <L1>:
; X64-NEXT:    355: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    35a: e9 0c 00 00 00 jmp <L4>
; X64-NEXT:  <L2>:
; X64-NEXT:    35f: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    364: e9 02 00 00 00 jmp <L4>
; X64-NEXT:  <L3>:
; X64-NEXT:    369: 89 d8 mov eax, ebx
; X64-NEXT:  <L4>:
; X64-NEXT:    36b: 5b pop rbx
; X64-NEXT:    36c: 5d pop rbp
; X64-NEXT:    36d: c3 ret
; X64-NEXT:    36e: 66 90 nop
;
; ARM64-LABEL: <switch_i32_noreuse>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    str x19, [sp, #0x10]
; ARM64-NEXT:    mov w19, w0
; ARM64-NEXT:    mov w0, w19
; ARM64-NEXT:    cmp w0, #0x1
; ARM64-NEXT:    b.eq <L1>
; ARM64-NEXT:    cmp w0, #0x2
; ARM64-NEXT:    b.eq <L2>
; ARM64-NEXT:    b <L0>
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    b <L3>
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    b <L4>
; ARM64-NEXT:  <L2>:
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    b <L4>
; ARM64-NEXT:  <L3>:
; ARM64-NEXT:    mov w0, w19
; ARM64-NEXT:  <L4>:
; ARM64-NEXT:    ldr x19, [sp, #0x10]
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
  switch i32 %p, label %default [
    i32 1, label %l1
    i32 2, label %l2
  ]
l1:
  ret i32 1
l2:
  ret i32 2
default:
  ret i32 %p
}

define i64 @switch_i64_noreuse(i64 %p) {
; X64-LABEL: <switch_i64_noreuse>:
; X64:         370: 55 push rbp
; X64-NEXT:    371: 48 89 e5 mov rbp, rsp
; X64-NEXT:    374: 53 push rbx
; X64-NEXT:    375: 48 89 fb mov rbx, rdi
; X64-NEXT:    378: 48 89 d8 mov rax, rbx
; X64-NEXT:    37b: 48 83 f8 01 cmp rax, 0x1
; X64-NEXT:    37f: 0f 84 14 00 00 00 je <L1>
; X64-NEXT:    385: 48 83 f8 02 cmp rax, 0x2
; X64-NEXT:    389: 0f 84 14 00 00 00 je <L2>
; X64-NEXT:    38f: e9 00 00 00 00 jmp <L0>
; X64-NEXT:  <L0>:
; X64-NEXT:    394: e9 14 00 00 00 jmp <L3>
; X64-NEXT:  <L1>:
; X64-NEXT:    399: b8 01 00 00 00 mov eax, 0x1
; X64-NEXT:    39e: e9 0d 00 00 00 jmp <L4>
; X64-NEXT:  <L2>:
; X64-NEXT:    3a3: b8 02 00 00 00 mov eax, 0x2
; X64-NEXT:    3a8: e9 03 00 00 00 jmp <L4>
; X64-NEXT:  <L3>:
; X64-NEXT:    3ad: 48 89 d8 mov rax, rbx
; X64-NEXT:  <L4>:
; X64-NEXT:    3b0: 5b pop rbx
; X64-NEXT:    3b1: 5d pop rbp
; X64-NEXT:    3b2: c3 ret
; X64-NEXT:    3b3: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    3bc: 0f 1f 40 00 nop dword ptr [rax]
;
; ARM64-LABEL: <switch_i64_noreuse>:
; ARM64:         stp x29, x30, [sp, #-0xa0]!
; ARM64-NEXT:    mov x29, sp
; ARM64-NEXT:    str x19, [sp, #0x10]
; ARM64-NEXT:    mov x19, x0
; ARM64-NEXT:    mov x0, x19
; ARM64-NEXT:    cmp x0, #0x1
; ARM64-NEXT:    b.eq <L1>
; ARM64-NEXT:    cmp x0, #0x2
; ARM64-NEXT:    b.eq <L2>
; ARM64-NEXT:    b <L0>
; ARM64-NEXT:  <L0>:
; ARM64-NEXT:    b <L3>
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    mov x0, #0x1 // =1
; ARM64-NEXT:    b <L4>
; ARM64-NEXT:  <L2>:
; ARM64-NEXT:    mov x0, #0x2 // =2
; ARM64-NEXT:    b <L4>
; ARM64-NEXT:  <L3>:
; ARM64-NEXT:    mov x0, x19
; ARM64-NEXT:  <L4>:
; ARM64-NEXT:    ldr x19, [sp, #0x10]
; ARM64-NEXT:    ldp x29, x30, [sp], #0xa0
; ARM64-NEXT:    ret
  switch i64 %p, label %default [
    i64 1, label %l1
    i64 2, label %l2
  ]
l1:
  ret i64 1
l2:
  ret i64 2
default:
  ret i64 %p
}

define i32 @switch_to_self() {
; X64-LABEL: <switch_to_self>:
; X64:       <L0>:
; X64-NEXT:    3c0: 31 c9 xor ecx, ecx
; X64-NEXT:    3c2: 48 89 ca mov rdx, rcx
; X64-NEXT:    3c5: 83 fa 35 cmp edx, 0x35
; X64-NEXT:    3c8: 0f 84 be 00 00 00 je <L4>
; X64-NEXT:    3ce: 0f 87 1e 00 00 00 ja <L1>
; X64-NEXT:    3d4: 83 ea 0a sub edx, 0xa
; X64-NEXT:    3d7: 83 fa 2a cmp edx, 0x2a
; X64-NEXT:    3da: 0f 87 4f 00 00 00 ja <L3>
; X64-NEXT:    3e0: 48 8d 35 e5 00 00 00 lea rsi, <switch_to_self+0x10c>
; X64-NEXT:    3e7: 8b 14 96 mov edx, dword ptr [rsi + 4*rdx]
; X64-NEXT:    3ea: 48 29 d6 sub rsi, rdx
; X64-NEXT:    3ed: ff e6 jmp rsi
; X64-NEXT:    3ef: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:  <L1>:
; X64-NEXT:    3f2: 83 fa 62 cmp edx, 0x62
; X64-NEXT:    3f5: 0f 84 bd 00 00 00 je <L8>
; X64-NEXT:    3fb: 0f 87 17 00 00 00 ja <L2>
; X64-NEXT:    401: 83 fa 36 cmp edx, 0x36
; X64-NEXT:    404: 0f 84 92 00 00 00 je <L5>
; X64-NEXT:    40a: 83 fa 37 cmp edx, 0x37
; X64-NEXT:    40d: 0f 84 99 00 00 00 je <L6>
; X64-NEXT:    413: e9 17 00 00 00 jmp <L3>
; X64-NEXT:  <L2>:
; X64-NEXT:    418: 83 fa 66 cmp edx, 0x66
; X64-NEXT:    41b: 0f 84 9e 00 00 00 je <L9>
; X64-NEXT:    421: 83 fa 72 cmp edx, 0x72
; X64-NEXT:    424: 0f 84 87 00 00 00 je <L7>
; X64-NEXT:    42a: e9 00 00 00 00 jmp <L3>
; X64-NEXT:  <L3>:
; X64-NEXT:    42f: e9 92 00 00 00 jmp <L10>
; X64-NEXT:    434: 0f 1f 84 00 00 00 00 00 nop dword ptr [rax + rax]
; X64-NEXT:    43c: eb 82 jmp <switch_to_self>
; X64-NEXT:    43e: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    447: 0f 1f 44 00 00 nop dword ptr [rax + rax]
; X64-NEXT:    44c: e9 75 00 00 00 jmp <L10>
; X64-NEXT:    451: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    45a: 66 90 nop
; X64-NEXT:    45c: e9 65 00 00 00 jmp <L10>
; X64-NEXT:    461: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    46a: 66 90 nop
; X64-NEXT:    46c: e9 55 00 00 00 jmp <L10>
; X64-NEXT:    471: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    47a: 66 90 nop
; X64-NEXT:    47c: e9 45 00 00 00 jmp <L10>
; X64-NEXT:    481: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    48a: 66 90 nop
; X64-NEXT:  <L4>:
; X64-NEXT:    48c: e9 35 00 00 00 jmp <L10>
; X64-NEXT:    491: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    49a: 66 90 nop
; X64-NEXT:  <L5>:
; X64-NEXT:    49c: e9 25 00 00 00 jmp <L10>
; X64-NEXT:    4a1: 66 0f 1f 84 00 00 00 00 00 nop word ptr [rax + rax]
; X64-NEXT:    4aa: 66 90 nop
; X64-NEXT:  <L6>:
; X64-NEXT:    4ac: e9 15 00 00 00 jmp <L10>
; X64-NEXT:  <L7>:
; X64-NEXT:    4b1: 31 c0 xor eax, eax
; X64-NEXT:    4b3: e9 10 00 00 00 jmp <L11>
; X64-NEXT:  <L8>:
; X64-NEXT:    4b8: 31 c0 xor eax, eax
; X64-NEXT:    4ba: e9 09 00 00 00 jmp <L11>
; X64-NEXT:  <L9>:
; X64-NEXT:    4bf: 31 c0 xor eax, eax
; X64-NEXT:    4c1: e9 02 00 00 00 jmp <L11>
; X64-NEXT:  <L10>:
; X64-NEXT:    4c6: 31 c0 xor eax, eax
; X64-NEXT:  <L11>:
; X64-NEXT:    4c8: c3 ret
; X64-NEXT:    4c9: 0f 1f 00 nop dword ptr [rax]
; X64-NEXT:    4cc: 90 nop
; X64-NEXT:    4cd: 00 00 add byte ptr [rax], al
; X64-NEXT:    4cf: 00 9d 00 00 00 9d add byte ptr [rbp - 0x63000000], bl
; X64-NEXT:    4d5: 00 00 add byte ptr [rax], al
; X64-NEXT:    4d7: 00 9d 00 00 00 9d add byte ptr [rbp - 0x63000000], bl
; X64-NEXT:    4dd: 00 00 add byte ptr [rax], al
; X64-NEXT:    4df: 00 9d 00 00 00 9d add byte ptr [rbp - 0x63000000], bl
; X64-NEXT:    4e5: 00 00 add byte ptr [rax], al
; X64-NEXT:    4e7: 00 9d 00 00 00 9d add byte ptr [rbp - 0x63000000], bl
; X64-NEXT:    4ed: 00 00 add byte ptr [rax], al
; X64-NEXT:    4ef: 00 9d 00 00 00 9d add byte ptr [rbp - 0x63000000], bl
; X64-NEXT:    4f5: 00 00 add byte ptr [rax], al
; X64-NEXT:    4f7: 00 9d 00 00 00 9d add byte ptr [rbp - 0x63000000], bl
; X64-NEXT:    4fd: 00 00 add byte ptr [rax], al
; X64-NEXT:    4ff: 00 9d 00 00 00 9d add byte ptr [rbp - 0x63000000], bl
; X64-NEXT:    505: 00 00 add byte ptr [rax], al
; X64-NEXT:    507: 00 9d 00 00 00 9d add byte ptr [rbp - 0x63000000], bl
; X64-NEXT:    50d: 00 00 add byte ptr [rax], al
; X64-NEXT:    50f: 00 9d 00 00 00 9d add byte ptr [rbp - 0x63000000], bl
; X64-NEXT:    515: 00 00 add byte ptr [rax], al
; X64-NEXT:    517: 00 9d 00 00 00 9d add byte ptr [rbp - 0x63000000], bl
; X64-NEXT:    51d: 00 00 add byte ptr [rax], al
; X64-NEXT:    51f: 00 9d 00 00 00 9d add byte ptr [rbp - 0x63000000], bl
; X64-NEXT:    525: 00 00 add byte ptr [rax], al
; X64-NEXT:    527: 00 9d 00 00 00 9d add byte ptr [rbp - 0x63000000], bl
; X64-NEXT:    52d: 00 00 add byte ptr [rax], al
; X64-NEXT:    52f: 00 9d 00 00 00 9d add byte ptr [rbp - 0x63000000], bl
; X64-NEXT:    535: 00 00 add byte ptr [rax], al
; X64-NEXT:    537: 00 9d 00 00 00 9d add byte ptr [rbp - 0x63000000], bl
; X64-NEXT:    53d: 00 00 add byte ptr [rax], al
; X64-NEXT:    53f: 00 9d 00 00 00 9d add byte ptr [rbp - 0x63000000], bl
; X64-NEXT:    545: 00 00 add byte ptr [rax], al
; X64-NEXT:    547: 00 9d 00 00 00 9d add byte ptr [rbp - 0x63000000], bl
; X64-NEXT:    54d: 00 00 add byte ptr [rax], al
; X64-NEXT:    54f: 00 9d 00 00 00 9d add byte ptr [rbp - 0x63000000], bl
; X64-NEXT:    555: 00 00 add byte ptr [rax], al
; X64-NEXT:    557: 00 9d 00 00 00 9d add byte ptr [rbp - 0x63000000], bl
; X64-NEXT:    55d: 00 00 add byte ptr [rax], al
; X64-NEXT:    55f: 00 9d 00 00 00 06 add byte ptr [rbp + 0x6000000], bl
; X64-NEXT:    565: 00 00 add byte ptr [rax], al
; X64-NEXT:    567: 00 80 00 00 00 70 add byte ptr [rax + 0x70000000], al
; X64-NEXT:    56d: 00 00 add byte ptr [rax], al
; X64-NEXT:    56f: 00 60 00 add byte ptr [rax], ah
; X64-NEXT:    572: 00 00 add byte ptr [rax], al
; X64-NEXT:    574: 50 push rax
; X64-NEXT:    575: 00 00 add byte ptr [rax], al
; X64-NEXT:    577: 00 <unknown>
;
; ARM64-LABEL: <switch_to_self>:
; ARM64:       <L0>:
; ARM64-NEXT:    mov w1, #0x0 // =0
; ARM64-NEXT:    mov x2, x1
; ARM64-NEXT:    cmp w2, #0x35
; ARM64-NEXT:    b.eq <L5>
; ARM64-NEXT:    b.hi <L2>
; ARM64-NEXT:    sub w2, w2, #0xa
; ARM64-NEXT:    cmp w2, #0x2a
; ARM64-NEXT:    b.hi <L4>
; ARM64-NEXT:    adrp x3, 0x0 <empty_switch>
; ARM64-NEXT:     R_AARCH64_ADR_PREL_PG_HI21
; ARM64-NEXT:    add x3, x3, #0x0
; ARM64-NEXT:     R_AARCH64_ADD_ABS_LO12_NC
; ARM64-NEXT:    ldrb w2, [x3, w2, uxtw #0]
; ARM64-NEXT:  <L1>:
; ARM64-NEXT:    adr x3, <L1>
; ARM64-NEXT:    add x3, x3, x2, lsl #2
; ARM64-NEXT:    br x3
; ARM64-NEXT:  <L2>:
; ARM64-NEXT:    cmp w2, #0x62
; ARM64-NEXT:    b.eq <L9>
; ARM64-NEXT:    b.hi <L3>
; ARM64-NEXT:    cmp w2, #0x36
; ARM64-NEXT:    b.eq <L6>
; ARM64-NEXT:    cmp w2, #0x37
; ARM64-NEXT:    b.eq <L7>
; ARM64-NEXT:    b <L4>
; ARM64-NEXT:  <L3>:
; ARM64-NEXT:    cmp w2, #0x66
; ARM64-NEXT:    b.eq <L10>
; ARM64-NEXT:    cmp w2, #0x72
; ARM64-NEXT:    b.eq <L8>
; ARM64-NEXT:    b <L4>
; ARM64-NEXT:  <L4>:
; ARM64-NEXT:    b <L11>
; ARM64-NEXT:    b <switch_to_self>
; ARM64-NEXT:     ...
; ARM64-NEXT:    b <L11>
; ARM64-NEXT:     ...
; ARM64-NEXT:    b <L11>
; ARM64-NEXT:     ...
; ARM64-NEXT:    b <L11>
; ARM64-NEXT:     ...
; ARM64-NEXT:    b <L11>
; ARM64-NEXT:     ...
; ARM64-NEXT:  <L5>:
; ARM64-NEXT:    b <L11>
; ARM64-NEXT:     ...
; ARM64-NEXT:  <L6>:
; ARM64-NEXT:    b <L11>
; ARM64-NEXT:     ...
; ARM64-NEXT:  <L7>:
; ARM64-NEXT:    b <L11>
; ARM64-NEXT:  <L8>:
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    b <L12>
; ARM64-NEXT:  <L9>:
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    b <L12>
; ARM64-NEXT:  <L10>:
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:    b <L12>
; ARM64-NEXT:  <L11>:
; ARM64-NEXT:    mov w0, #0x0 // =0
; ARM64-NEXT:  <L12>:
; ARM64-NEXT:    ret
  br label %1

1:
  switch i32 0, label %5 [
    i32 55, label %5
    i32 114, label %2
    i32 54, label %5
    i32 98, label %3
    i32 102, label %4
    i32 10, label %1
    i32 48, label %5
    i32 49, label %5
    i32 50, label %5
    i32 51, label %5
    i32 52, label %5
    i32 53, label %5
  ]

2:
  ret i32 0

3:
  ret i32 0

4:
  ret i32 0

5:
  ret i32 0
}
